# This file is autogenerated, do not edit by hand!
{fetchgit}: {
  registryUrl = "https://github.com/JuliaRegistries/General.git";
  registryRev = "5301377d5bee18a6a793bed19ac49e66efbda118";
  registrySha256 = "1w49famwz5pd03vmv3gnl4gpkyxs3hqzkmyc8pc2af66527d2cn4";
  rootPackages = ["CodeTracking" "Distributions" "MLStyle" "SimplePosets" "SymbolicUtils" "Test"];
  closure = [{
  name = "AbstractAlgebra";
  uuid = "c3fe647b-3220-5bb0-a1ea-a7954cac585d";
  path = "A/AbstractAlgebra";
  replaceUrlInManifest = null;
  treehash = "75c0cb641ccbed4ee00a45099fe1b197e0317d38";
  artifacts = {};
  src = fetchgit { url = "https://github.com/Nemocas/AbstractAlgebra.jl.git"; rev = "75c0cb641ccbed4ee00a45099fe1b197e0317d38"; sha256 = "0kvnihni33kqibbdnkvg6gkkb4436434vk1zafi6xvm222v9z1fz"; };
} {
  name = "AbstractLattices";
  uuid = "398f06c4-4d28-53ec-89ca-5b2656b7603d";
  path = "A/AbstractLattices";
  replaceUrlInManifest = null;
  treehash = "f35684b7349da49fcc8a9e520e30e45dbb077166";
  artifacts = {};
  src = fetchgit { url = "https://github.com/scheinerman/AbstractLattices.jl.git"; rev = "f35684b7349da49fcc8a9e520e30e45dbb077166"; sha256 = "1hndgwy3lx6k09idbbybr57imsxrj34bkdf8kikzxk7ynddzmj48"; };
} {
  name = "AbstractTrees";
  uuid = "1520ce14-60c1-5f80-bbc7-55ef81b5835c";
  path = "A/AbstractTrees";
  replaceUrlInManifest = null;
  treehash = "33e450545eaf7699da1a6e755f9ea65f14077a45";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaCollections/AbstractTrees.jl.git"; rev = "33e450545eaf7699da1a6e755f9ea65f14077a45"; sha256 = "094x150vpg9jwlr7s68b5461igc1fkiavysvx818i22bs5q8jvn1"; };
} {
  name = "Adapt";
  uuid = "79e6a3ab-5dfb-504d-930d-738a2a938a0e";
  path = "A/Adapt";
  replaceUrlInManifest = null;
  treehash = "ffcfa2d345aaee0ef3d8346a073d5dd03c983ebe";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaGPU/Adapt.jl.git"; rev = "ffcfa2d345aaee0ef3d8346a073d5dd03c983ebe"; sha256 = "1z245s3z35ks9wblfzlnkck912a6pv3rc9n05zxba3sngwd7fa1s"; };
} {
  name = "ArrayInterface";
  uuid = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9";
  path = "A/ArrayInterface";
  replaceUrlInManifest = null;
  treehash = "a2a1884863704e0414f6f164a1f6f4a2a62faf4e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaArrays/ArrayInterface.jl.git"; rev = "a2a1884863704e0414f6f164a1f6f4a2a62faf4e"; sha256 = "1zm49arf6iwswlvx5f23l1dq33yy6p023mjwwqhnivslp0xjxfky"; };
} {
  name = "Artifacts";
  uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33";
  path = "A/Artifacts";
  replaceUrlInManifest = null;
  treehash = "c30985d8821e0cd73870b17b0ed0ce6dc44cb744";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/Artifacts.jl.git"; rev = "c30985d8821e0cd73870b17b0ed0ce6dc44cb744"; sha256 = "0i0s26ypiwg6zyb3aqn9kiyiblkkab1mfac9plmq2jv4hggm4jfc"; };
} {
  name = "Base64";
  uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Calculus";
  uuid = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9";
  path = "C/Calculus";
  replaceUrlInManifest = null;
  treehash = "f641eb0a4f00c343bbc32346e1217b86f3ce9dad";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/Calculus.jl.git"; rev = "f641eb0a4f00c343bbc32346e1217b86f3ce9dad"; sha256 = "0xh0ak2ycsjw2h86ja24ch3kn2d18zx3frrds78aimwdnqb1gdc2"; };
} {
  name = "CodeTracking";
  uuid = "da1fd8a2-8d9e-5ec2-8556-3022fb5608a2";
  path = "C/CodeTracking";
  replaceUrlInManifest = null;
  treehash = "8ad457cfeb0bca98732c97958ef81000a543e73e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/timholy/CodeTracking.jl.git"; rev = "8ad457cfeb0bca98732c97958ef81000a543e73e"; sha256 = "1znjdfg1yn3vq88apqdxiz6y4n9n63s6h07bvp5jz8v0khrn0qzf"; };
} {
  name = "Combinatorics";
  uuid = "861a8166-3701-5b0c-9a16-15d98fcdc6aa";
  path = "C/Combinatorics";
  replaceUrlInManifest = null;
  treehash = "08c8b6831dc00bfea825826be0bc8336fc369860";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/Combinatorics.jl.git"; rev = "08c8b6831dc00bfea825826be0bc8336fc369860"; sha256 = "0gafqkqi874zfm9h99akw9q95lk3ih5gip2h8p12fj9h7rvyf4j5"; };
} {
  name = "CommonSubexpressions";
  uuid = "bbf7d656-a473-5ed7-a52c-81e309532950";
  path = "C/CommonSubexpressions";
  replaceUrlInManifest = null;
  treehash = "7b8a93dba8af7e3b42fecabf646260105ac373f7";
  artifacts = {};
  src = fetchgit { url = "https://github.com/rdeits/CommonSubexpressions.jl.git"; rev = "7b8a93dba8af7e3b42fecabf646260105ac373f7"; sha256 = "0mgy90kk8ksv3l720kkk04gnhn4aqhh2dj4sp3x8yy3limngfjay"; };
} {
  name = "Compat";
  uuid = "34da2185-b29b-5c13-b0c7-acf172513d20";
  path = "C/Compat";
  replaceUrlInManifest = null;
  treehash = "919c7f3151e79ff196add81d7f4e45d91bbf420b";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaLang/Compat.jl.git"; rev = "919c7f3151e79ff196add81d7f4e45d91bbf420b"; sha256 = "1m4r5i8mq29xjp3mllh6047n5a78sdyld57m15anrnsjgaapcgby"; };
} {
  name = "CompilerSupportLibraries_jll";
  uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae";
  path = "C/CompilerSupportLibraries_jll";
  replaceUrlInManifest = null;
  treehash = "8e695f735fca77e9708e795eda62afdb869cbb70";
  artifacts = {
    "0fd0fb67de786e5d7b2eb67181d35e4bcab639cf" = [{
      name = "CompilerSupportLibraries";
      url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl/releases/download/CompilerSupportLibraries-v0.3.3+0/CompilerSupportLibraries.v0.3.3.x86_64-linux-gnu-libgfortran4.tar.gz";
      sha256 = "adcc8519411cf0518c472d3ce47d8ac93492934a05c0276afe76eda6d91c4f4d";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/CompilerSupportLibraries_jll.jl.git"; rev = "8e695f735fca77e9708e795eda62afdb869cbb70"; sha256 = "0iqm61cjxilqcapz9z9w42qq799dmzfd92px2gysjdmny3v0qf4r"; };
} {
  name = "DataAPI";
  uuid = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a";
  path = "D/DataAPI";
  replaceUrlInManifest = null;
  treehash = "dfb3b7e89e395be1e25c2ad6d7690dc29cc53b1d";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/DataAPI.jl.git"; rev = "dfb3b7e89e395be1e25c2ad6d7690dc29cc53b1d"; sha256 = "14sfvkz169zcbap3gdwpj16qsap783h86fd07flfxk822abam11w"; };
} {
  name = "DataStructures";
  uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8";
  path = "D/DataStructures";
  replaceUrlInManifest = null;
  treehash = "4437b64df1e0adccc3e5d1adbc3ac741095e4677";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaCollections/DataStructures.jl.git"; rev = "4437b64df1e0adccc3e5d1adbc3ac741095e4677"; sha256 = "0hdqp8ipsqdw5bqqkdvz4j6n67x80sj5azr9vzyxwjfsgkfbnk2l"; };
} {
  name = "Dates";
  uuid = "ade2ca70-3891-5945-98fb-dc099432e06a";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "DelimitedFiles";
  uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "DiffEqDiffTools";
  uuid = "01453d9d-ee7c-5054-8395-0335cb756afa";
  path = "D/DiffEqDiffTools";
  replaceUrlInManifest = null;
  treehash = "a4ed8a740484627ea41b47f7e1a25dd909a28353";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaDiff/FiniteDiff.jl.git"; rev = "a4ed8a740484627ea41b47f7e1a25dd909a28353"; sha256 = "05d08gpknj3p4zjn6rppc2h0v75qmvykb3l0326hxlm73wkvvjgf"; };
} {
  name = "DiffResults";
  uuid = "163ba53b-c6d8-5494-b064-1a9d43ac40c5";
  path = "D/DiffResults";
  replaceUrlInManifest = null;
  treehash = "c18e98cba888c6c25d1c3b048e4b3380ca956805";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaDiff/DiffResults.jl.git"; rev = "c18e98cba888c6c25d1c3b048e4b3380ca956805"; sha256 = "1w6p3yxajvclax5b9g7cr2jmbc7lvr5nk4gq0aljxdycdq1d2y3v"; };
} {
  name = "DiffRules";
  uuid = "b552c78f-8df3-52c6-915a-8e097449b14b";
  path = "D/DiffRules";
  replaceUrlInManifest = null;
  treehash = "214c3fcac57755cfda163d91c58893a8723f93e9";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaDiff/DiffRules.jl.git"; rev = "214c3fcac57755cfda163d91c58893a8723f93e9"; sha256 = "0cwjvj4gma7924fm3yas0nf0jlnwwx4v7fi79ii3s290lkdldzfl"; };
} {
  name = "Distributed";
  uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Distributions";
  uuid = "31c24e10-a181-5473-b8eb-7969acd0382f";
  path = "D/Distributions";
  replaceUrlInManifest = null;
  treehash = "9c41285c57c6e0d73a21ed4b65f6eec34805f937";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/Distributions.jl.git"; rev = "9c41285c57c6e0d73a21ed4b65f6eec34805f937"; sha256 = "0ri9frw5cfi9ychvhminfzds0hvx9581cd33f7zqm4pylhzlcwiz"; };
} {
  name = "ExprTools";
  uuid = "e2ba6199-217a-4e67-a87a-7c52f15ade04";
  path = "E/ExprTools";
  replaceUrlInManifest = null;
  treehash = "10407a39b87f29d47ebaca8edbc75d7c302ff93e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/invenia/ExprTools.jl.git"; rev = "10407a39b87f29d47ebaca8edbc75d7c302ff93e"; sha256 = "1lwxi9fx9farf1jdv42gv43xs3f3i3js2xnvr5gf6d0xfx0g6b6a"; };
} {
  name = "EzXML";
  uuid = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615";
  path = "E/EzXML";
  replaceUrlInManifest = null;
  treehash = "0fa3b52a04a4e210aeb1626def9c90df3ae65268";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/EzXML.jl.git"; rev = "0fa3b52a04a4e210aeb1626def9c90df3ae65268"; sha256 = "0h6qdhcyndhm7irv6ybckajcnknsbl0zgdy5dcgpjs7n1ysh853r"; };
} {
  name = "FillArrays";
  uuid = "1a297f60-69ca-5386-bcde-b61e274b549b";
  path = "F/FillArrays";
  replaceUrlInManifest = null;
  treehash = "4863cbb7910079369e258dee4add9d06ead5063a";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaArrays/FillArrays.jl.git"; rev = "4863cbb7910079369e258dee4add9d06ead5063a"; sha256 = "0hqkwjfw0q066600bq04fbf06zps9g78gj585ff1v451r3cwvrx6"; };
} {
  name = "FlexLinearAlgebra";
  uuid = "b67e1e5a-d13e-5892-ad81-fb75f5903773";
  path = "F/FlexLinearAlgebra";
  replaceUrlInManifest = null;
  treehash = "0a9c6dac1dcd94b496add97faf72bad9cd5bd4de";
  artifacts = {};
  src = fetchgit { url = "https://github.com/scheinerman/FlexLinearAlgebra.jl.git"; rev = "0a9c6dac1dcd94b496add97faf72bad9cd5bd4de"; sha256 = "0j8dxk8ddj8wfps50hqb7lr48wpqzn2b2qbq9jvadyil888nsn5k"; };
} {
  name = "ForwardDiff";
  uuid = "f6369f11-7733-5829-9624-2563aa707210";
  path = "F/ForwardDiff";
  replaceUrlInManifest = null;
  treehash = "d48a40c0f54f29a5c8748cfb3225719accc72b77";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaDiff/ForwardDiff.jl.git"; rev = "d48a40c0f54f29a5c8748cfb3225719accc72b77"; sha256 = "1bm16q2pi743sfw475snjfnjwg1p0c5vl1ipws6kain99hpxr7w3"; };
} {
  name = "IfElse";
  uuid = "615f187c-cbe4-4ef1-ba3b-2fcf58d6d173";
  path = "I/IfElse";
  replaceUrlInManifest = null;
  treehash = "28e837ff3e7a6c3cdb252ce49fb412c8eb3caeef";
  artifacts = {};
  src = fetchgit { url = "https://github.com/SciML/IfElse.jl.git"; rev = "28e837ff3e7a6c3cdb252ce49fb412c8eb3caeef"; sha256 = "1wrw842r8708fryf2ihp9mkmdrg27saa9nix2c31vs995k2fgr9w"; };
} {
  name = "InteractiveUtils";
  uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Intervals";
  uuid = "d8418881-c3e1-53bb-8760-2df7ec849ed5";
  path = "I/Intervals";
  replaceUrlInManifest = null;
  treehash = "323a38ed1952d30586d0fe03412cde9399d3618b";
  artifacts = {};
  src = fetchgit { url = "https://github.com/invenia/Intervals.jl.git"; rev = "323a38ed1952d30586d0fe03412cde9399d3618b"; sha256 = "1nj40fjx0q3gszq0r8h6scnzyldp68yv1y2lpmmbxraf47644q0n"; };
} {
  name = "IterTools";
  uuid = "c8e1da08-722c-5040-9ed9-7db0dc04731e";
  path = "I/IterTools";
  replaceUrlInManifest = null;
  treehash = "05110a2ab1fc5f932622ffea2a003221f4782c18";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaCollections/IterTools.jl.git"; rev = "05110a2ab1fc5f932622ffea2a003221f4782c18"; sha256 = "0haf974kcqj6arv4if97ahs4w3dmvslh6ab3hl57r9s41ic36xdq"; };
} {
  name = "JLLWrappers";
  uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210";
  path = "J/JLLWrappers";
  replaceUrlInManifest = null;
  treehash = "a431f5f2ca3f4feef3bd7a5e94b8b8d4f2f647a0";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/JLLWrappers.jl.git"; rev = "a431f5f2ca3f4feef3bd7a5e94b8b8d4f2f647a0"; sha256 = "1sj3mi2dcc13apqfpy401wic5n0pgbck1p98b2g3zw0mln9s83m4"; };
} {
  name = "LabelledArrays";
  uuid = "2ee39098-c373-598a-b85f-a56591580800";
  path = "L/LabelledArrays";
  replaceUrlInManifest = null;
  treehash = "5e288800819c323de5897fa6d5a002bdad54baf7";
  artifacts = {};
  src = fetchgit { url = "https://github.com/SciML/LabelledArrays.jl.git"; rev = "5e288800819c323de5897fa6d5a002bdad54baf7"; sha256 = "0gr74v0kijqznz3cplnsj4hnp2qzsyj6asr8kj7nadarrz871lkm"; };
} {
  name = "LibGit2";
  uuid = "76f85450-5226-5b5a-8eaa-529ad045b433";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Libdl";
  uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Libiconv_jll";
  uuid = "94ce4f54-9a6c-5748-9c1c-f9c7231a4531";
  path = "L/Libiconv_jll";
  replaceUrlInManifest = null;
  treehash = "8e924324b2e9275a51407a4e06deb3455b1e359f";
  artifacts = {
    "473dc2ed3d46252c87733b7fdca3da64c6f9f917" = [{
      name = "Libiconv";
      url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl/releases/download/Libiconv-v1.16.0+5/Libiconv.v1.16.0.x86_64-linux-gnu.tar.gz";
      sha256 = "518b0c2f04ba6057dc5ed63f4dc23e4abac49840b6b5470ce8cf1ad8412c6227";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Libiconv_jll.jl.git"; rev = "8e924324b2e9275a51407a4e06deb3455b1e359f"; sha256 = "07xd1lbp8ldavxpik9h40wx80mfaf0isz9jza4g7xgfcbyfqh1d8"; };
} {
  name = "LightXML";
  uuid = "9c8b4983-aa76-5018-a973-4c85ecc9e179";
  path = "L/LightXML";
  replaceUrlInManifest = null;
  treehash = "e129d9391168c677cd4800f5c0abb1ed8cb3794f";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaIO/LightXML.jl.git"; rev = "e129d9391168c677cd4800f5c0abb1ed8cb3794f"; sha256 = "0lr513683pgqqclxjcmzhaqvl85qncgllahkgby263jfmm8l8929"; };
} {
  name = "LineSearches";
  uuid = "d3d80556-e9d4-5f37-9878-2ab0fcc64255";
  path = "L/LineSearches";
  replaceUrlInManifest = null;
  treehash = "f27132e551e959b3667d8c93eae90973225032dd";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaNLSolvers/LineSearches.jl.git"; rev = "f27132e551e959b3667d8c93eae90973225032dd"; sha256 = "1qc4la07w6s1xhcyd0hvbnpr31zc1a2ssgyybc8biv5m00g0dnr0"; };
} {
  name = "LinearAlgebra";
  uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "LinearAlgebraX";
  uuid = "9b3f67b0-2d00-526e-9884-9e4938f8fb88";
  path = "L/LinearAlgebraX";
  replaceUrlInManifest = null;
  treehash = "abfc2e340036e308a8c25952a4dd724a1b7f78be";
  artifacts = {};
  src = fetchgit { url = "https://github.com/scheinerman/LinearAlgebraX.jl.git"; rev = "abfc2e340036e308a8c25952a4dd724a1b7f78be"; sha256 = "1v2ypxy1nx8wl4hhmy1kf383sxx13lpx66xpw4ss3bn37cbwrk01"; };
} {
  name = "Logging";
  uuid = "56ddb016-857b-54e1-b83d-db4d58db5568";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "MLStyle";
  uuid = "d8e11817-5142-5d16-987a-aa16d5891078";
  path = "M/MLStyle";
  replaceUrlInManifest = null;
  treehash = "937eda9ce36fcce082a42edd7181c8d23f4eb550";
  artifacts = {};
  src = fetchgit { url = "https://github.com/thautwarm/MLStyle.jl.git"; rev = "937eda9ce36fcce082a42edd7181c8d23f4eb550"; sha256 = "1bfcd80f7a1brsp2f9mpvlh1bxzwjrn3z0kyyf05w3vahmcy3l9g"; };
} {
  name = "MacroTools";
  uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09";
  path = "M/MacroTools";
  replaceUrlInManifest = null;
  treehash = "6a8a2a625ab0dea913aba95c11370589e0239ff0";
  artifacts = {};
  src = fetchgit { url = "https://github.com/FluxML/MacroTools.jl.git"; rev = "6a8a2a625ab0dea913aba95c11370589e0239ff0"; sha256 = "0k4z2hyasd9cwxf4l61zk3w4ajs44k69wx6z1ghdn8f5p8xy217f"; };
} {
  name = "Markdown";
  uuid = "d6f4376e-aef5-505a-96c1-9c027394607a";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Missings";
  uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28";
  path = "M/Missings";
  replaceUrlInManifest = null;
  treehash = "f8c673ccc215eb50fcadb285f522420e29e69e1c";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaData/Missings.jl.git"; rev = "f8c673ccc215eb50fcadb285f522420e29e69e1c"; sha256 = "1qsnvpmqrps631yvka11hb5jcsfskgpn29c99fvm73vd9xqp6cin"; };
} {
  name = "Mmap";
  uuid = "a63ad114-7e13-5084-954f-fe012c677804";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Mocking";
  uuid = "78c3b35d-d492-501b-9361-3d52fe80e533";
  path = "M/Mocking";
  replaceUrlInManifest = null;
  treehash = "916b850daad0d46b8c71f65f719c49957e9513ed";
  artifacts = {};
  src = fetchgit { url = "https://github.com/invenia/Mocking.jl.git"; rev = "916b850daad0d46b8c71f65f719c49957e9513ed"; sha256 = "10jz716v6i3gpd403rmcrip6cncjl9lqr12cdl321x1994a5g8ck"; };
} {
  name = "Mods";
  uuid = "7475f97c-0381-53b1-977b-4c60186c8d62";
  path = "M/Mods";
  replaceUrlInManifest = null;
  treehash = "e4ea1ff49413228f18e8db1167be0dcdfbfe0d75";
  artifacts = {};
  src = fetchgit { url = "https://github.com/scheinerman/Mods.jl.git"; rev = "e4ea1ff49413228f18e8db1167be0dcdfbfe0d75"; sha256 = "0ck2jwpl8nqzlxjhr617m6ybsalslfpw1ps4q2zwrw80xr42m7ki"; };
} {
  name = "Multisets";
  uuid = "3b2b4ff1-bcff-5658-a3ee-dbcf1ce5ac09";
  path = "M/Multisets";
  replaceUrlInManifest = null;
  treehash = "fd47d7822f15254e0ed66f7e38af57a603481c59";
  artifacts = {};
  src = fetchgit { url = "https://github.com/scheinerman/Multisets.jl.git"; rev = "fd47d7822f15254e0ed66f7e38af57a603481c59"; sha256 = "1sya9npvys5y1vcmw13kq0ywlmlblv76wlyk6yhcv1ibk7v1mx5y"; };
} {
  name = "NLSolversBase";
  uuid = "d41bc354-129a-5804-8e4c-c37616107c6c";
  path = "N/NLSolversBase";
  replaceUrlInManifest = null;
  treehash = "f1b8ed89fa332f410cfc7c937682eb4d0b361521";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaNLSolvers/NLSolversBase.jl.git"; rev = "f1b8ed89fa332f410cfc7c937682eb4d0b361521"; sha256 = "1sm6h1qmfh1w0nqpcf61b7zfd2w97h0p7j9apq23ha2cddnvyzck"; };
} {
  name = "NaNMath";
  uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3";
  path = "N/NaNMath";
  replaceUrlInManifest = null;
  treehash = "bfe47e760d60b82b66b61d2d44128b62e3a369fb";
  artifacts = {};
  src = fetchgit { url = "https://github.com/mlubin/NaNMath.jl.git"; rev = "bfe47e760d60b82b66b61d2d44128b62e3a369fb"; sha256 = "1hczhz00qj99w63vp627kwk02l2sr2qmzc2rkwwkdwvzy670p25q"; };
} {
  name = "OffsetArrays";
  uuid = "6fe1bfb0-de20-5000-8ca7-80f57d26f881";
  path = "O/OffsetArrays";
  replaceUrlInManifest = null;
  treehash = "986e7c0a0ef1863be969d191957ac32cb17d0d79";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaArrays/OffsetArrays.jl.git"; rev = "986e7c0a0ef1863be969d191957ac32cb17d0d79"; sha256 = "0hdw8mygg09zgcx8ildq4phqky5wah9c2534sdnqlbkww82xjir6"; };
} {
  name = "OpenSpecFun_jll";
  uuid = "efe28fd5-8261-553b-a9e1-b2916fc3738e";
  path = "O/OpenSpecFun_jll";
  replaceUrlInManifest = null;
  treehash = "9db77584158d0ab52307f8c04f8e7c08ca76b5b3";
  artifacts = {
    "846b9ab259c1612b851f8b59bc3658997e23ff57" = [{
      name = "OpenSpecFun";
      url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl/releases/download/OpenSpecFun-v0.5.3+3/OpenSpecFun.v0.5.3.x86_64-linux-gnu-libgfortran4.tar.gz";
      sha256 = "4f7927ae3ea60d2a44f207afd8e94f4209fb87112f630eac4cdba2b4e03ef5b6";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/OpenSpecFun_jll.jl.git"; rev = "9db77584158d0ab52307f8c04f8e7c08ca76b5b3"; sha256 = "0bl2gcgndsbiwhwy8fl070cjm1fyf9kxj6gkikgirmzgjl29iakn"; };
} {
  name = "Optim";
  uuid = "429524aa-4258-5aef-a3af-852621145aeb";
  path = "O/Optim";
  replaceUrlInManifest = null;
  treehash = "c05aa6b694d426df87ff493306c1c5b4b215e148";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaNLSolvers/Optim.jl.git"; rev = "c05aa6b694d426df87ff493306c1c5b4b215e148"; sha256 = "1mslm2q00xw8clhaqmsx7mn8lzjjcxdsc4xcckldbm3s6ipkf7i8"; };
} {
  name = "OrderedCollections";
  uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d";
  path = "O/OrderedCollections";
  replaceUrlInManifest = null;
  treehash = "4fa2ba51070ec13fcc7517db714445b4ab986bdf";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaCollections/OrderedCollections.jl.git"; rev = "4fa2ba51070ec13fcc7517db714445b4ab986bdf"; sha256 = "1mc0q32mcgawc9161xrpnrsrrn6jli1rhfbslv4f4fii94q78wd4"; };
} {
  name = "PDMats";
  uuid = "90014a1f-27ba-587c-ab20-58faa44d9150";
  path = "P/PDMats";
  replaceUrlInManifest = null;
  treehash = "95a4038d1011dfdbde7cecd2ad0ac411e53ab1bc";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/PDMats.jl.git"; rev = "95a4038d1011dfdbde7cecd2ad0ac411e53ab1bc"; sha256 = "0lkivy3lw62wlw04scl3hdfdmwjz2kfa29h73akc0d53qvq36ji7"; };
} {
  name = "Parameters";
  uuid = "d96e819e-fc66-5662-9728-84c9c7592b0a";
  path = "P/Parameters";
  replaceUrlInManifest = null;
  treehash = "2276ac65f1e236e0a6ea70baff3f62ad4c625345";
  artifacts = {};
  src = fetchgit { url = "https://github.com/mauro3/Parameters.jl.git"; rev = "2276ac65f1e236e0a6ea70baff3f62ad4c625345"; sha256 = "0b8lawi7kcws4axfsdf023gyxca15irl648ciyi1kw3wghz3pfi2"; };
} {
  name = "Permutations";
  uuid = "2ae35dd2-176d-5d53-8349-f30d82d94d4f";
  path = "P/Permutations";
  replaceUrlInManifest = null;
  treehash = "f5852b6188601f4944186c69e2591ee05be54ded";
  artifacts = {};
  src = fetchgit { url = "https://github.com/scheinerman/Permutations.jl.git"; rev = "f5852b6188601f4944186c69e2591ee05be54ded"; sha256 = "1hi3m5846j1yrr4i6vly2kchgwlhv7vqywml0mw46impnhl33yxi"; };
} {
  name = "Pkg";
  uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Polynomials";
  uuid = "f27b6e38-b328-58d1-80ce-0feddd5e7a45";
  path = "P/Polynomials";
  replaceUrlInManifest = null;
  treehash = "1c6c5b0c3713738d6b987903c529d80622c37e07";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/Polynomials.jl.git"; rev = "1c6c5b0c3713738d6b987903c529d80622c37e07"; sha256 = "19sb4m6vvs1li2cqf9z9qb1x4j2x0yim2zjd5blrbgnmjlhmyfix"; };
} {
  name = "PositiveFactorizations";
  uuid = "85a6dd25-e78a-55b7-8502-1745935b8125";
  path = "P/PositiveFactorizations";
  replaceUrlInManifest = null;
  treehash = "17275485f373e6673f7e7f97051f703ed5b15b20";
  artifacts = {};
  src = fetchgit { url = "https://github.com/timholy/PositiveFactorizations.jl.git"; rev = "17275485f373e6673f7e7f97051f703ed5b15b20"; sha256 = "1wxy6ak7f3hvibcgc8q88cgkf9zvi649mmjy1zlkx1qk80hgvz23"; };
} {
  name = "Primes";
  uuid = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae";
  path = "P/Primes";
  replaceUrlInManifest = null;
  treehash = "afccf037da52fa596223e5a0e331ff752e0e845c";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/Primes.jl.git"; rev = "afccf037da52fa596223e5a0e331ff752e0e845c"; sha256 = "0xqak6hpzc2fk2sfaq6ih7niv8vjrjc3kzb9l1dl5kwv6jdn995h"; };
} {
  name = "Printf";
  uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "QuadGK";
  uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc";
  path = "Q/QuadGK";
  replaceUrlInManifest = null;
  treehash = "12fbe86da16df6679be7521dfb39fbc861e1dc7b";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/QuadGK.jl.git"; rev = "12fbe86da16df6679be7521dfb39fbc861e1dc7b"; sha256 = "1hy0629yai6xflgxaflk9764lzr1lzhlghimxk1aqi212q9c6n33"; };
} {
  name = "REPL";
  uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Random";
  uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "RandomExtensions";
  uuid = "fb686558-2515-59ef-acaa-46db3789a887";
  path = "R/RandomExtensions";
  replaceUrlInManifest = null;
  treehash = "062986376ce6d394b23d5d90f01d81426113a3c9";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaRandom/RandomExtensions.jl.git"; rev = "062986376ce6d394b23d5d90f01d81426113a3c9"; sha256 = "0a4p72jcqzjm2apf0ysdkhzk04zzfb5p8qxjks16b94ini2yy2lv"; };
} {
  name = "RecipesBase";
  uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01";
  path = "R/RecipesBase";
  replaceUrlInManifest = null;
  treehash = "b3fb709f3c97bfc6e948be68beeecb55a0b340ae";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPlots/RecipesBase.jl.git"; rev = "b3fb709f3c97bfc6e948be68beeecb55a0b340ae"; sha256 = "1b6m5rz6wprj30rwvlxz4r1jv5gl0ay0f52kfmy2w7lqly7zhap5"; };
} {
  name = "Requires";
  uuid = "ae029012-a4dd-5104-9daa-d747884805df";
  path = "R/Requires";
  replaceUrlInManifest = null;
  treehash = "cfbac6c1ed70c002ec6361e7fd334f02820d6419";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaPackaging/Requires.jl.git"; rev = "cfbac6c1ed70c002ec6361e7fd334f02820d6419"; sha256 = "14r49cz3dnbnrbrjnjn513z0lb6dpawkx7vmcwgs1cmc0rdxcz4a"; };
} {
  name = "RingLists";
  uuid = "286e9d63-9694-5540-9e3c-4e6708fa07b2";
  path = "R/RingLists";
  replaceUrlInManifest = null;
  treehash = "8a41f1fd67b4c8db9c44a0cd15bc0b0c59991d23";
  artifacts = {};
  src = fetchgit { url = "https://github.com/scheinerman/RingLists.jl.git"; rev = "8a41f1fd67b4c8db9c44a0cd15bc0b0c59991d23"; sha256 = "1319bzqaw83hwkjhhmdw8qf9vzn94h71a8n1r538sbl55ybhqnxr"; };
} {
  name = "Rmath";
  uuid = "79098fc4-a85e-5d69-aa6a-4863f24498fa";
  path = "R/Rmath";
  replaceUrlInManifest = null;
  treehash = "86c5647b565873641538d8f812c04e4c9dbeb370";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/Rmath.jl.git"; rev = "86c5647b565873641538d8f812c04e4c9dbeb370"; sha256 = "1745xajy5c8hdcy1hgi2rr9lrapr55hp0jm2dcb1ksyskvm5drsr"; };
} {
  name = "Rmath_jll";
  uuid = "f50d1b31-88e8-58de-be2c-1cc44531875f";
  path = "R/Rmath_jll";
  replaceUrlInManifest = null;
  treehash = "d76185aa1f421306dec73c057aa384bad74188f0";
  artifacts = {
    "fa7a95c807b2fbc4e13451994fe92463203ce891" = [{
      name = "Rmath";
      url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl/releases/download/Rmath-v0.2.2+1/Rmath.v0.2.2.x86_64-linux-gnu.tar.gz";
      sha256 = "59490caae4d04fd46cebd63d94bf6f7bbb147bb9471e5cbe616e05b6a2a1eca5";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Rmath_jll.jl.git"; rev = "d76185aa1f421306dec73c057aa384bad74188f0"; sha256 = "13wvx4n0ai7bsda3rvlw8xbqwdbdwhjijbgjgl0k2yzq5l8x5dmh"; };
} {
  name = "SHA";
  uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce";
  path = "S/SHA";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "Serialization";
  uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SharedArrays";
  uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SimpleGraphs";
  uuid = "55797a34-41de-5266-9ec1-32ac4eb504d3";
  path = "S/SimpleGraphs";
  replaceUrlInManifest = null;
  treehash = "188ddab4713a1f2dd3c938b68695e3db0e111c6f";
  artifacts = {};
  src = fetchgit { url = "https://github.com/scheinerman/SimpleGraphs.jl.git"; rev = "188ddab4713a1f2dd3c938b68695e3db0e111c6f"; sha256 = "10w3vipy3xr55v2ahmlassm9d5mzmannmmps20ag1jpy2iddsxdz"; };
} {
  name = "SimplePartitions";
  uuid = "ec83eff0-a5b5-5643-ae32-5cbf6eedec9d";
  path = "S/SimplePartitions";
  replaceUrlInManifest = null;
  treehash = "dcc02923a53f316ab97da8ef3136e80b4543dbf1";
  artifacts = {};
  src = fetchgit { url = "https://github.com/scheinerman/SimplePartitions.jl.git"; rev = "dcc02923a53f316ab97da8ef3136e80b4543dbf1"; sha256 = "18b7672hflr0d5j63mkncss10f9dnj6kz70dlwz716i0l41mh9h6"; };
} {
  name = "SimplePolynomials";
  uuid = "cc47b68c-3164-5771-a705-2bc0097375a0";
  path = "S/SimplePolynomials";
  replaceUrlInManifest = null;
  treehash = "f0793aebac95b1093ea7d60ec00fa8564a50d291";
  artifacts = {};
  src = fetchgit { url = "https://github.com/scheinerman/SimplePolynomials.jl.git"; rev = "f0793aebac95b1093ea7d60ec00fa8564a50d291"; sha256 = "1wi203wccrfl80qnqq1f2h24f8plzq1vpy3r5j06n8525b8slsd3"; };
} {
  name = "SimplePosets";
  uuid = "b2aef97b-4721-5af9-b440-0bad754dc5ba";
  path = "S/SimplePosets";
  replaceUrlInManifest = null;
  treehash = "b8033596c4a0a3d52e4a23f9557cf2892febc38c";
  artifacts = {};
  src = fetchgit { url = "https://github.com/scheinerman/SimplePosets.jl.git"; rev = "b8033596c4a0a3d52e4a23f9557cf2892febc38c"; sha256 = "0nbvhcdpwm7bqdckyvx63r7jspy87lh826f13iwq3amdcajjhjds"; };
} {
  name = "SimpleRandom";
  uuid = "a6525b86-64cd-54fa-8f65-62fc48bdc0e8";
  path = "S/SimpleRandom";
  replaceUrlInManifest = null;
  treehash = "59a830985c7292e4028955b631d3f5edcf8ff35e";
  artifacts = {};
  src = fetchgit { url = "https://github.com/scheinerman/SimpleRandom.jl.git"; rev = "59a830985c7292e4028955b631d3f5edcf8ff35e"; sha256 = "18mjygin36jn4dvsq836vl2y2f51driy7y866qfkgarljmmmznyp"; };
} {
  name = "Sockets";
  uuid = "6462fe0b-24de-5631-8697-dd941f90decc";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SortingAlgorithms";
  uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c";
  path = "S/SortingAlgorithms";
  replaceUrlInManifest = null;
  treehash = "03f5898c9959f8115e30bc7226ada7d0df554ddd";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaCollections/SortingAlgorithms.jl.git"; rev = "03f5898c9959f8115e30bc7226ada7d0df554ddd"; sha256 = "1nz96sccgl6h6aknck59gmy1yrzx356kk9z68svj2g6yialprv1j"; };
} {
  name = "SparseArrays";
  uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SpecialFunctions";
  uuid = "276daf66-3868-5448-9aa4-cd146d93841b";
  path = "S/SpecialFunctions";
  replaceUrlInManifest = null;
  treehash = "d8d8b8a9f4119829410ecd706da4cc8594a1e020";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaMath/SpecialFunctions.jl.git"; rev = "d8d8b8a9f4119829410ecd706da4cc8594a1e020"; sha256 = "1m0f3g6ikfrg85cbizq6xafg5r1r0db0x91y85i6czzmimk3156w"; };
} {
  name = "StaticArrays";
  uuid = "90137ffa-7385-5640-81b9-e52037218182";
  path = "S/StaticArrays";
  replaceUrlInManifest = null;
  treehash = "da4cf579416c81994afd6322365d00916c79b8ae";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaArrays/StaticArrays.jl.git"; rev = "da4cf579416c81994afd6322365d00916c79b8ae"; sha256 = "1h2biy5pjikg29rms0302gmds1q3i243yaaabmxddkyay67srms4"; };
} {
  name = "Statistics";
  uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "StatsBase";
  uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91";
  path = "S/StatsBase";
  replaceUrlInManifest = null;
  treehash = "400aa43f7de43aeccc5b2e39a76a79d262202b76";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/StatsBase.jl.git"; rev = "400aa43f7de43aeccc5b2e39a76a79d262202b76"; sha256 = "1vc1dqi3zbza7dj5znqqwkv0k1zdrkqikza6fvxh3rps20g7wfrp"; };
} {
  name = "StatsFuns";
  uuid = "4c63d2b9-4356-54db-8cca-17b64c39e42c";
  path = "S/StatsFuns";
  replaceUrlInManifest = null;
  treehash = "3b9f665c70712af3264b61c27a7e1d62055dafd1";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaStats/StatsFuns.jl.git"; rev = "3b9f665c70712af3264b61c27a7e1d62055dafd1"; sha256 = "0fhkx4clxlfixlb9hw7bsljfkv468k2y9s3f2cpaz7f5qbvgkmmq"; };
} {
  name = "SuiteSparse";
  uuid = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "SymbolicUtils";
  uuid = "d1185830-fcd6-423d-90d6-eec64667417b";
  path = "S/SymbolicUtils";
  replaceUrlInManifest = null;
  treehash = "4df514f3c4821247f447791a950619a931195c00";
  artifacts = {};
  src = fetchgit { url = "https://github.com/JuliaSymbolics/SymbolicUtils.jl.git"; rev = "4df514f3c4821247f447791a950619a931195c00"; sha256 = "0hv808w8qbnd65wazp5qnb2i8sw052mhkz0mlgw4ahwzvxj4g707"; };
} {
  name = "Test";
  uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "TimeZones";
  uuid = "f269a46b-ccf7-5d73-abea-4c690281aa53";
  path = "T/TimeZones";
  replaceUrlInManifest = null;
  treehash = "4ba8a9579a243400db412b50300cd61d7447e583";
  artifacts = {
    "73129ab667ff6e4f3623e96b7d48c3578f6150ca" = [{
      name = "tzdata2015d";
      url = "https://data.iana.org/time-zones/releases/tzdata2015d.tar.gz";
      sha256 = "8b9f5008277f09e251e97dba7813f56168d691115bda90ade4638d72f296d531";
    }];
    "e7ddeb4a45080afa6dbdd7c38df81bcf8b9d8f1a" = [{
      name = "tzdata93g";
      url = "https://data.iana.org/time-zones/releases/tzdata93g.tar.gz";
      sha256 = "453cd56c946c0f0c062bd0d4b42555bb55b76778f91bc2f85aa390bc7de95140";
    }];
    "31285cab8eea6dce31e35c4773eeb0c40e2d4d08" = [{
      name = "tzdata2004b";
      url = "https://data.iana.org/time-zones/releases/tzdata2004b.tar.gz";
      sha256 = "2e0b133c09b35632e994e05ce732221c40b1bcdcab3030eaac1b9d0b816c2a7a";
    }];
    "276c761771ee0e9b0005960d073ff7e92d1134a2" = [{
      name = "tzdata2005e";
      url = "https://data.iana.org/time-zones/releases/tzdata2005e.tar.gz";
      sha256 = "54fa34db60e0d867c6384f7d91e04eba91e5b0bc7e9c90384f47186bde913691";
    }];
    "978ca11bd0b05d32c2f11ddfb88ea97b9ef20a6b" = [{
      name = "tzdata2011b";
      url = "https://data.iana.org/time-zones/releases/tzdata2011b.tar.gz";
      sha256 = "ff45f5ddc2ec925249626d00d7bc2ffff587e0956a1d8245517a023bf27e4cc9";
    }];
    "3665c7afaab6a1f06dee60021b4d2eedb01a9cc7" = [{
      name = "tzdata2002c";
      url = "https://data.iana.org/time-zones/releases/tzdata2002c.tar.gz";
      sha256 = "f85e764207a693f8cc10ac7259da28029bfb1c3409c02274ec45cb52689c5fa3";
    }];
    "9b0435894c57daa25578d4437524b4b9d37f0c24" = [{
      name = "tzdata2005i";
      url = "https://data.iana.org/time-zones/releases/tzdata2005i.tar.gz";
      sha256 = "8f416e8816d4ee3a53f218639d2aa00731e951a884d689ac76e2766b2169d610";
    }];
    "b1cc2250912bf1b61c6687d6a5e360ee0ce906d0" = [{
      name = "tzdata2012f";
      url = "https://data.iana.org/time-zones/releases/tzdata2012f.tar.gz";
      sha256 = "afe95a49a445ee55391d2d4beccd4be6d61a090d5d8069c407390ff1502c26cc";
    }];
    "6ac70b261703c39615f2e7797aa3662f57e97a9a" = [{
      name = "tzdata95e";
      url = "https://data.iana.org/time-zones/releases/tzdata95e.tar.gz";
      sha256 = "74a714c1913275256b5838bab29d97096519f1bc92d87e3df2992e5840fb761f";
    }];
    "aae2aa1c4adca2691342d0381e5fbcb223322419" = [{
      name = "tzdata2010n";
      url = "https://data.iana.org/time-zones/releases/tzdata2010n.tar.gz";
      sha256 = "5946bff5cef28feda6cff241f03c84e528cd4fcc0c2b27b537f52994f8afc70b";
    }];
    "8d32dc27d64088c22f4dad04253bd28c083ffc23" = [{
      name = "tzdata2018e";
      url = "https://data.iana.org/time-zones/releases/tzdata2018e.tar.gz";
      sha256 = "6b288e5926841a4cb490909fe822d85c36ae75538ad69baf20da9628b63b692e";
    }];
    "1be0ada460ed4f4907c4ed480d615a2cc5c99b0c" = [{
      name = "tzdata2007e";
      url = "https://data.iana.org/time-zones/releases/tzdata2007e.tar.gz";
      sha256 = "51d14a60ea12aa901bf91e5d39ea30c13ffdc299640e8ec9cb0d35a128874767";
    }];
    "916b8d04fae4f987a90380ac7743d03f1ab7fab2" = [{
      name = "tzdata2009o";
      url = "https://data.iana.org/time-zones/releases/tzdata2009o.tar.gz";
      sha256 = "5fbd4053a4eb01b814799855e35a3c01743f98acf9fcd167522e6484a2edd7b7";
    }];
    "f70f34e93ba2a198f18939d025cfb779526ff06c" = [{
      name = "tzdata1999i";
      url = "https://data.iana.org/time-zones/releases/tzdata1999i.tar.gz";
      sha256 = "1026cdf0e426202a6ebf987f35d4e7d364a1c2cde43ee12e3c58eca979367a9f";
    }];
    "cf0a1e6c32af07f93ddeb9ecbaf13a97cacdd630" = [{
      name = "tzdata2006j";
      url = "https://data.iana.org/time-zones/releases/tzdata2006j.tar.gz";
      sha256 = "afa77e59020f7d111ba8059cc8877b4f6dd972a3d3a14c118a2b876269c9ee84";
    }];
    "c833ad3be0ba34cf91e05889bb43145b44dbb09b" = [{
      name = "tzdata2009i";
      url = "https://data.iana.org/time-zones/releases/tzdata2009i.tar.gz";
      sha256 = "475b52311b2e0267cfb81138af1b985384ea53ce71b2d39744d7645f1e48db6e";
    }];
    "cda12ceaf5011117f92b3c2fe493fc093ccb3fa2" = [{
      name = "tzdata2006g";
      url = "https://data.iana.org/time-zones/releases/tzdata2006g.tar.gz";
      sha256 = "028a5d8bc3771876cf43b497e8b8691acae8263af34b0a8de3e014f01a5558d0";
    }];
    "64fc7257e66321f4e71620d4ddeeefad277d437e" = [{
      name = "tzdata2007i";
      url = "https://data.iana.org/time-zones/releases/tzdata2007i.tar.gz";
      sha256 = "70bb254ae0da44d71f6d0932ffe34f61457bf41c38dfd389a7bf5bfb544a362b";
    }];
    "9c858b9af8c0d15139ab246d2bb70cc3f5d9ebf3" = [{
      name = "tzdata2013g";
      url = "https://data.iana.org/time-zones/releases/tzdata2013g.tar.gz";
      sha256 = "b6cdd3998dcc732a6ae5e101e1394f9d4d6dff68bd48a8fb78c44c2b997d3a4f";
    }];
    "4d9088654728df3e80820989aee0600722c05c92" = [{
      name = "tzdata2005h";
      url = "https://data.iana.org/time-zones/releases/tzdata2005h.tar.gz";
      sha256 = "6e6a21957097f8c7e8d5b78c814aabf6647130a2db12000d4244f261ea0367d6";
    }];
    "642fcaa05e913808dbe7d810f9bfdaa69da975f8" = [{
      name = "tzdata2016b";
      url = "https://data.iana.org/time-zones/releases/tzdata2016b.tar.gz";
      sha256 = "6392091d92556a32de488ea06a055c51bc46b7d8046c8a677f0ccfe286b3dbdc";
    }];
    "bd457274ad54c27ed0b413fc9fac9305b3f6c56c" = [{
      name = "tzdata2005f";
      url = "https://data.iana.org/time-zones/releases/tzdata2005f.tar.gz";
      sha256 = "1ce924ac48678710d228483d65ef79bf2cfc4735fda0dec2d8af3343c57d2f3c";
    }];
    "293ce4ca6ace46bf3ce152f86665c9398a2bc99a" = [{
      name = "tzdata2009n";
      url = "https://data.iana.org/time-zones/releases/tzdata2009n.tar.gz";
      sha256 = "7b08bb8a98ad8a06e2cafda05ab21f2a69b2d64252dfc9435c93094d979e7c5a";
    }];
    "8fcc7370d049d05b8b1ca872b49060c3536be2f3" = [{
      name = "tzdata2009l";
      url = "https://data.iana.org/time-zones/releases/tzdata2009l.tar.gz";
      sha256 = "a0caab89a45261137f38f61d19329fffe0e45e2c6d6e7a9b70ebef37c0fdde5f";
    }];
    "02232194ac597e358d30e1f7da36e8ef2ecea1ca" = [{
      name = "tzdata1999f";
      url = "https://data.iana.org/time-zones/releases/tzdata1999f.tar.gz";
      sha256 = "c710988ec840f8c268acb20c3e580fe3d6421473e1d1b0b52f9a25f47c98e5ab";
    }];
    "a7cafb0f0a64faf3a997bb6365bf12da1f0fcd1a" = [{
      name = "tzdata2007h";
      url = "https://data.iana.org/time-zones/releases/tzdata2007h.tar.gz";
      sha256 = "8f16f0db83073c8ccb3702f9173c4991200c78e64ebd358fce9cbbf4371a2148";
    }];
    "da5486252cd73bc05cb7c4625f84353cd07b60b7" = [{
      name = "tzdata2007g";
      url = "https://data.iana.org/time-zones/releases/tzdata2007g.tar.gz";
      sha256 = "082943adc009753b046227f143051ef41d9c549292f0415242188aaac9e2ee5b";
    }];
    "e8be8dd48e75c8de6596190dd8e4e61f796d34e6" = [{
      name = "tzdata2009f";
      url = "https://data.iana.org/time-zones/releases/tzdata2009f.tar.gz";
      sha256 = "654b309a0c130a156cc81787f8af4dc9a517d283606f420e89364bc93c83da6c";
    }];
    "51e2040d0f52458d3177e5ec16f36c23f1cbbbd4" = [{
      name = "tzdata2010l";
      url = "https://data.iana.org/time-zones/releases/tzdata2010l.tar.gz";
      sha256 = "bae7b4a8364f7ab3d6d644eb6075de1e9a0c72fb3fb5843fc217d2ff57408577";
    }];
    "7b6c645aa38fe80d9ab522b45ad05fdaece40c48" = [{
      name = "tzdata2009u";
      url = "https://data.iana.org/time-zones/releases/tzdata2009u.tar.gz";
      sha256 = "7cbd82597590ca279e042dbeace91553806c4b4dbff25c34b843a4f1d07e0384";
    }];
    "f0f2360afc47afe32557f639ab19e8f1323cb330" = [{
      name = "tzdata1999d";
      url = "https://data.iana.org/time-zones/releases/tzdata1999d.tar.gz";
      sha256 = "42b558313ecf1e4e927b3acc6f48ddb34f4db9e377121852443460c735deeef2";
    }];
    "b41f9f08304c5c309b8d3304b573699f57cb36b7" = [{
      name = "tzdata2007k";
      url = "https://data.iana.org/time-zones/releases/tzdata2007k.tar.gz";
      sha256 = "37e986086ce1a1ccb9a4f24c2b77ede54f0eae2ee9959e7a191a49cedb405783";
    }];
    "b042f5b9f046b1051d99b73516d2c7cccfff2869" = [{
      name = "tzdata2005r";
      url = "https://data.iana.org/time-zones/releases/tzdata2005r.tar.gz";
      sha256 = "5cd4058b54fd2ce9d63af112847aaa2141db955726c416071c37050a2756e648";
    }];
    "17321bcd802497dc4f56c4465d0905caa470066b" = [{
      name = "tzdata2001c";
      url = "https://data.iana.org/time-zones/releases/tzdata2001c.tar.gz";
      sha256 = "481ed23a9e705e0bb86e3634f89ff3028e86dbe31ce9088db9834620985b47bd";
    }];
    "237b36be50ceefe169041b91c80e3e98c7b28b44" = [{
      name = "tzdata2006f";
      url = "https://data.iana.org/time-zones/releases/tzdata2006f.tar.gz";
      sha256 = "95eb97eae2efbd355b2f7e3aef50b2cb971246966dcd0cd692d6f178df341f0c";
    }];
    "f052bec9396067db314ae37cba669e1fdb528742" = [{
      name = "tzdata95f";
      url = "https://data.iana.org/time-zones/releases/tzdata95f.tar.gz";
      sha256 = "6f64cc52d9f9a5083e24e35f6db4ac5b93733896249df5ced0828cb3aa6c93a8";
    }];
    "61c25a33348a187669c4975e16c5fb1476bb5201" = [{
      name = "tzdata2015g";
      url = "https://data.iana.org/time-zones/releases/tzdata2015g.tar.gz";
      sha256 = "b923cdbf078491696b17bc8d069c74bce73fabc5774629da2f410c9b31576161";
    }];
    "2d1ac481d3dfb4d949aea596a5ac4456ace20dbd" = [{
      name = "tzdata2016d";
      url = "https://data.iana.org/time-zones/releases/tzdata2016d.tar.gz";
      sha256 = "d9554dfba0efd76053582bd89e8c7036ef12eee14fdd506675b08a5b59f0a1b4";
    }];
    "614e10267d8173c9d75167149cae0f5da9f6b68e" = [{
      name = "unicode-cldr-release-37";
      url = "https://github.com/unicode-org/cldr/archive/release-37.tar.gz";
      sha256 = "28e1617f70f18cd96162972b1deeb3f2bacc5b9fe02a1494b6dbfcff79ea0f7a";
    }];
    "24b2183dfcce9cf59400546351479c4142b04003" = [{
      name = "tzdata2016f";
      url = "https://data.iana.org/time-zones/releases/tzdata2016f.tar.gz";
      sha256 = "ed8c951008d12f1db55a11e96fc055718c6571233327d9de16a7f8475e2502b0";
    }];
    "f8e0116f6deda1b223f843658effb45b48163116" = [{
      name = "tzdata1998c";
      url = "https://data.iana.org/time-zones/releases/tzdata1998c.tar.gz";
      sha256 = "554807903af354384520f2bf03419f041616616394a341345a7ee20fd2a47ef7";
    }];
    "cf7def70f6f91cb73b8db6db6692575724993cf2" = [{
      name = "tzdata2011m";
      url = "https://data.iana.org/time-zones/releases/tzdata2011m.tar.gz";
      sha256 = "c8e01f5b4a3cd8b8aee84b4befb4b671cef34353e5af022ed22071f5b86ef5f4";
    }];
    "0050463a62ae4b3d4c682f489d322ffab3deffe5" = [{
      name = "tzdata2010e";
      url = "https://data.iana.org/time-zones/releases/tzdata2010e.tar.gz";
      sha256 = "09ebe8787560ef0a0b8b27a115d0d79d4b9e4ed9d48e768426c59ad18b73abd6";
    }];
    "c9fe5f15341dc73b8cbf332fc932b6d1ecfa70df" = [{
      name = "tzdata2009h";
      url = "https://data.iana.org/time-zones/releases/tzdata2009h.tar.gz";
      sha256 = "4eaa785fccc13fe26a1c92518e59108b78422115eaf9cb5a6bb95168bb5e92ab";
    }];
    "e455c906578d147be45bdfb24333ef1f4883eeaf" = [{
      name = "tzdata2010o";
      url = "https://data.iana.org/time-zones/releases/tzdata2010o.tar.gz";
      sha256 = "cd0f3799688b3b870cd988505e47c2975b1808e73ec0677bc9db4b705b534c07";
    }];
    "5b8ef0a6c63a6d860528daf448c88582976708ae" = [{
      name = "tzdata2014e";
      url = "https://data.iana.org/time-zones/releases/tzdata2014e.tar.gz";
      sha256 = "08e243a79051f838d86ac1311a78b74047951302d448024e823b5b7aa71f86c5";
    }];
    "709cee3e17d5888f872e2544595690a5ae92ad3a" = [{
      name = "tzdata2008d";
      url = "https://data.iana.org/time-zones/releases/tzdata2008d.tar.gz";
      sha256 = "913b384dfcf541d340f251bc20cf2475d8f13a38ad38acfc2d901fc3c7bc4a71";
    }];
    "a66c62bfd0d160fe006cea0914c71854f81953b2" = [{
      name = "tzdata2018i";
      url = "https://data.iana.org/time-zones/releases/tzdata2018i.tar.gz";
      sha256 = "82c45ef84ca3bc01d0a4a397ba8adeb8f7f199c6550740587c6ac5a7108c00d9";
    }];
    "5584e5b3aa1c43a7343208f481012c4dcd49604c" = [{
      name = "tzdata2018c";
      url = "https://data.iana.org/time-zones/releases/tzdata2018c.tar.gz";
      sha256 = "2825c3e4b7ef520f24d393bcc02942f9762ffd3e7fc9b23850789ed8f22933f6";
    }];
    "ca401f65a295565ce881c9dab1cdeab64bb5c183" = [{
      name = "tzdata2000g";
      url = "https://data.iana.org/time-zones/releases/tzdata2000g.tar.gz";
      sha256 = "41c608cbacd4a6ccc39e835062841ee08c76f289e1ede77aa51435bdffbc5dab";
    }];
    "0ba32e0ebe914a327893a7d1bf77cf319ef395a8" = [{
      name = "tzdata2011g";
      url = "https://data.iana.org/time-zones/releases/tzdata2011g.tar.gz";
      sha256 = "01a2a189eeda63baacc5e68e6c13afffc7edce182102fffc53acbf35e8703d3c";
    }];
    "1297e8df94ee949425959c71f3e7a414e9332f0b" = [{
      name = "tzdata2011f";
      url = "https://data.iana.org/time-zones/releases/tzdata2011f.tar.gz";
      sha256 = "9b7431f25afbc154290a4075e43dc8841ed11d602faaf5a861db7a334a6d37a4";
    }];
    "28c8af4e53b63eef3c98b279170875dc0449598b" = [{
      name = "tzdata2007c";
      url = "https://data.iana.org/time-zones/releases/tzdata2007c.tar.gz";
      sha256 = "3575df0a341fef53240620423da519c6cba16212ab8b2576c9595b80deaf3af2";
    }];
    "506825ef0f22a6bdfe8cea991aacf483d455ddb8" = [{
      name = "tzdata2011n";
      url = "https://data.iana.org/time-zones/releases/tzdata2011n.tar.gz";
      sha256 = "a343e542486b2b8ebdeca474eed79f1c04f69420ca943c2b9bdea1d2385e38cd";
    }];
    "d21e24382e4f5f62b11ef48b54d92c2a98fc1761" = [{
      name = "tzdata1999g";
      url = "https://data.iana.org/time-zones/releases/tzdata1999g.tar.gz";
      sha256 = "63c60c56d256a59c4a7deef06380b14aa52fe4ffbe32aeb0ab61bb0901480578";
    }];
    "4bab760da0fc9a851df15d4a49b04f2fde77e9bc" = [{
      name = "tzdata2020b";
      url = "https://data.iana.org/time-zones/releases/tzdata2020b.tar.gz";
      sha256 = "9b053f951d245ce89d850b96ee4711d82d833559b1fc96ba19f90bc4d745e809";
    }];
    "41df1c2e7f1ab4ae8e9c3ed1904c807238a11e16" = [{
      name = "tzdata1996n";
      url = "https://data.iana.org/time-zones/releases/tzdata1996n.tar.gz";
      sha256 = "9f26873c22d1cb313bc4713eb575c2cfc98e1ce590aac4fd0cfb9f5ed7557d6e";
    }];
    "43ddd29e6f7efca9f917412beb5285189e3d4254" = [{
      name = "tzdata1997i";
      url = "https://data.iana.org/time-zones/releases/tzdata1997i.tar.gz";
      sha256 = "aeb468b7f52097c46793a5d585840e0562728cf0129f2c2b5da8e8658542bca2";
    }];
    "9b99f20e11aa8f57b27403ab496eb43833ef675b" = [{
      name = "tzdata2005l";
      url = "https://data.iana.org/time-zones/releases/tzdata2005l.tar.gz";
      sha256 = "9fca3fd22acc1a8488ee5cdfe523701acef936299944384235fe5cb37b1fc748";
    }];
    "c8bc147b13f6ad58cbf4a00837449acc70b10583" = [{
      name = "tzdata2011d";
      url = "https://data.iana.org/time-zones/releases/tzdata2011d.tar.gz";
      sha256 = "415a54774094e8dcdc9ba141fafbee4b3b2f2140a5b8cf012eea4b37fb9a23bd";
    }];
    "0779712241bffbd77e9639b67d2d4372777b969a" = [{
      name = "tzdata2008h";
      url = "https://data.iana.org/time-zones/releases/tzdata2008h.tar.gz";
      sha256 = "64070f1f31ab64f6c36f50cd462df9a74a6fa3613d73384c8dd62c3e8f716df3";
    }];
    "3792c6bcf2dd410edabc0de920b3262e9bcf08b9" = [{
      name = "tzdata94a";
      url = "https://data.iana.org/time-zones/releases/tzdata94a.tar.gz";
      sha256 = "402e8b5e7a713bde8514832e50a8d4a56900deb8e1d60c9abe5a36a5cb195a06";
    }];
    "4ff551e97f8fd00ea3049a044df6ade603555500" = [{
      name = "tzdata2018a";
      url = "https://data.iana.org/time-zones/releases/tzdata2018a.tar.gz";
      sha256 = "d2ea23a06783603a42c1a2665392e65958b0c8a341b2f2e7342d43343d7080dc";
    }];
    "ae7b60dc0c96fc76c945b5f95b464c2672a1f12b" = [{
      name = "tzdata94d";
      url = "https://data.iana.org/time-zones/releases/tzdata94d.tar.gz";
      sha256 = "5a9bb009b8423b3f4d262b9cc9098384e073e26aaee991a4fe73c2619fbe02cd";
    }];
    "f0c2ec1a9f4f35b55e8b3a2bbf1dde988d3319d0" = [{
      name = "tzdata2007d";
      url = "https://data.iana.org/time-zones/releases/tzdata2007d.tar.gz";
      sha256 = "33e6f84422c84bc02d83bb03fd741479896a9bb485fea3424afc406c32fb2278";
    }];
    "2fb6063591916dc30e7663adc314a23f86d72793" = [{
      name = "tzdata1997e";
      url = "https://data.iana.org/time-zones/releases/tzdata1997e.tar.gz";
      sha256 = "4172655ddfe5dd78bc64881e1b7dad8279a8240da1a8f69cd9b0682870f9452c";
    }];
    "d05faca96ef7a35480b3bf36756a75756ea084d2" = [{
      name = "tzdata2013c";
      url = "https://data.iana.org/time-zones/releases/tzdata2013c.tar.gz";
      sha256 = "e597a7eb239155eb2247fd4788f7fa10bf21d6469961200a6ca202f19cc15c87";
    }];
    "ed5094090a386b0046403e2ec8a245a85398de68" = [{
      name = "tzdata2012c";
      url = "https://data.iana.org/time-zones/releases/tzdata2012c.tar.gz";
      sha256 = "33e19e1dd27bda5239812587d72971509a15b59baff7abd692b77ff66f168a82";
    }];
    "db3c52afca438555adc49b5ef6b42e66b747fa73" = [{
      name = "tzdata2010m";
      url = "https://data.iana.org/time-zones/releases/tzdata2010m.tar.gz";
      sha256 = "1454a13a32e23e81195404d00ab97a64a356e9a5852fc7d121ed7e58cbdb75aa";
    }];
    "d6e40575c974dc69fe359462a242f19a113814e3" = [{
      name = "tzdata2005c";
      url = "https://data.iana.org/time-zones/releases/tzdata2005c.tar.gz";
      sha256 = "9d883f614f6a73cef98e137466e464954900bf8ddf25cd6c4e87f103c81dc7a1";
    }];
    "e1454e5128d1692a0ceee0c5dab015fef66cc79c" = [{
      name = "tzdata2000b";
      url = "https://data.iana.org/time-zones/releases/tzdata2000b.tar.gz";
      sha256 = "7b0a6e582b0973106e63965d94e362903ee5e387f10999bacb8796e23eebdcdb";
    }];
    "8103fcb8cfd76f77b84ae37897fe4b1ae2f02153" = [{
      name = "tzdata2015a";
      url = "https://data.iana.org/time-zones/releases/tzdata2015a.tar.gz";
      sha256 = "c52490917d00a8e7fc9b5f0b1b65ef6ec76d612b5b20c81bf86a04147af18e4c";
    }];
    "b360806993f1b54cf96dcaf7a0485f2f6e6bf235" = [{
      name = "tzdata2014a";
      url = "https://data.iana.org/time-zones/releases/tzdata2014a.tar.gz";
      sha256 = "7cff254ce85e11b21c994b284bccd1e12ecda9dadf947fbb32e1912fd520e8b1";
    }];
    "224a8021b537b72eaf90775b3ee3c076bad26cc1" = [{
      name = "tzdata2010g";
      url = "https://data.iana.org/time-zones/releases/tzdata2010g.tar.gz";
      sha256 = "a069dbea2989613466f9f4adb6de381efb46aeb9ff89e03fabb23dcae2c4cd90";
    }];
    "70cabdcca17757e721ba256830353930e87038e7" = [{
      name = "tzdata2014j";
      url = "https://data.iana.org/time-zones/releases/tzdata2014j.tar.gz";
      sha256 = "a2d870320694d40535df822ac8074dc629a90e92abafa5d3373314f78ddc0e0d";
    }];
    "2ad4eaf2fd0db4fd756019cca85d1139303e0c6f" = [{
      name = "tzdata95g";
      url = "https://data.iana.org/time-zones/releases/tzdata95g.tar.gz";
      sha256 = "48d06cc55d8007ff5be029f30a91cf8bd6cb1a5b9d69ac93b6d84ba51e99ad25";
    }];
    "ab7ad828525be554c36380e06ecb112be2df67f2" = [{
      name = "tzdata2006m";
      url = "https://data.iana.org/time-zones/releases/tzdata2006m.tar.gz";
      sha256 = "b0c42aa6e48d1eb4ad79aa3961541ff536f139c955a49893171814dead78d6a1";
    }];
    "1ad1a3f95648f825590f3766d24d2178ef759eeb" = [{
      name = "tzdata1997g";
      url = "https://data.iana.org/time-zones/releases/tzdata1997g.tar.gz";
      sha256 = "a6bb1b29a9e2288f4ade4611d6dc6b7c2fd72b2e3f7e40b9eeb8df2d24867251";
    }];
    "1cdce5cb827eb36655e4ac3bae4c179f68b00ab6" = [{
      name = "tzdata2020c";
      url = "https://data.iana.org/time-zones/releases/tzdata2020c.tar.gz";
      sha256 = "7890ac105f1aa4a5d15c5be2409580af401ee2f3fffe2a1e4748af589e194bd9";
    }];
    "b12b5ac230ccc80abb7fcafecf5291a893bbe66b" = [{
      name = "tzdata2003e";
      url = "https://data.iana.org/time-zones/releases/tzdata2003e.tar.gz";
      sha256 = "0a1216c18395ec1dfe0557ba37aed932db1237d6a4d6bcd8d02d36c589079d79";
    }];
    "ab1fdbdcdf5c8c57c66cfe27b0640ae76e6660a0" = [{
      name = "tzdata2010a";
      url = "https://data.iana.org/time-zones/releases/tzdata2010a.tar.gz";
      sha256 = "d9dab04cbbc52a7f19363958402b1c9cc6724e587f2af822c3e40e52767dfee8";
    }];
    "f6615351c754a9458dffdcca196e0ae970a5a731" = [{
      name = "tzdata2005p";
      url = "https://data.iana.org/time-zones/releases/tzdata2005p.tar.gz";
      sha256 = "d0713c9e0e99990185ab00e5a5cedb17d2b502b49826874170af2de50612a734";
    }];
    "a6e571519d7f510b2e1ebaa49db74e92e07a7d3b" = [{
      name = "tzdata2004e";
      url = "https://data.iana.org/time-zones/releases/tzdata2004e.tar.gz";
      sha256 = "1c50a26f165f38cfd9bf65b913f58fa849463c5d395faf38dd579916427aced8";
    }];
    "120dc3d384840054741fa6d3b1d4bb8eba2396b6" = [{
      name = "tzdata94f";
      url = "https://data.iana.org/time-zones/releases/tzdata94f.tar.gz";
      sha256 = "803238ec721289aac9a8f81f0325fca8476f2c6779368b3a1f384e0966b4c31f";
    }];
    "9fadafb63216a8590909eb5b47931b74ea890b4d" = [{
      name = "tzdata2013h";
      url = "https://data.iana.org/time-zones/releases/tzdata2013h.tar.gz";
      sha256 = "6b9e17e823eec0e09e12f74b452a70be4face1ef14c2fb1917b7c7e60564de27";
    }];
    "3bb4442c51d88ef5c319dd2080b5e778327ab8cc" = [{
      name = "tzdata2020d";
      url = "https://data.iana.org/time-zones/releases/tzdata2020d.tar.gz";
      sha256 = "8d813957de363387696f05af8a8889afa282ab5016a764c701a20758d39cbaf3";
    }];
    "3067e95a7ceebc5b9c6b9a8bda89f84f66894ed4" = [{
      name = "tzdata2009p";
      url = "https://data.iana.org/time-zones/releases/tzdata2009p.tar.gz";
      sha256 = "7182ad6f03bfe16ccdbac4a3efb9e765ea7c51afc33c3a7fefb053122aa6da2c";
    }];
    "eb7ed525a9ada80055e1100174b68335b48f1e1f" = [{
      name = "tzdata2005g";
      url = "https://data.iana.org/time-zones/releases/tzdata2005g.tar.gz";
      sha256 = "60e842ee850a0910e90c898e258ec4b9548264e285bd0d0db2d8dac460ce5679";
    }];
    "e7a30b675eaac813b7dc3e749d8d4a4684e14e94" = [{
      name = "tzdata2000a";
      url = "https://data.iana.org/time-zones/releases/tzdata2000a.tar.gz";
      sha256 = "da127977a0bd4832fadb45b81ebc084dbbca8b02cb23487a0d83174929ff5dc6";
    }];
    "004eafdccbb9f9bd68b9c3a01a25312d2126fc8f" = [{
      name = "tzdata2001a";
      url = "https://data.iana.org/time-zones/releases/tzdata2001a.tar.gz";
      sha256 = "49cd0f48fd1d7f81e5aad3b1244cb1338b770b8e3e1f5e0c9af9b7222e3062ea";
    }];
    "db6499a675a5b0a29a09435db680de34aa4409de" = [{
      name = "tzdata2006d";
      url = "https://data.iana.org/time-zones/releases/tzdata2006d.tar.gz";
      sha256 = "67993be3fd800f82f552171cab781a5736b1a5c0bc834e29e83a4be5d7b5b321";
    }];
    "1609767fd9881858d3339747368ce55c2e43f465" = [{
      name = "tzdata2011i";
      url = "https://data.iana.org/time-zones/releases/tzdata2011i.tar.gz";
      sha256 = "f8dde7ca5e61f21ac34c8cdbef5568d00c829981211098f059d8104964c81ffa";
    }];
    "20780fe7a8774baffbeecc2f9a7367d4e8162500" = [{
      name = "tzdata1999a";
      url = "https://data.iana.org/time-zones/releases/tzdata1999a.tar.gz";
      sha256 = "ae74120ccb18998eea9ce654d299392a4d5dc20b539eacd76e88bde1071485ef";
    } {
      name = "tzdata1998i";
      url = "https://data.iana.org/time-zones/releases/tzdata1998i.tar.gz";
      sha256 = "d2dde4ba94058ba2ad128f3d0bf9198892514a58ad3a65802a100a8a0277d4e1";
    }];
    "e9c33069a661dfae70aa6054ffa41acfbc6755ea" = [{
      name = "tzdata1999b";
      url = "https://data.iana.org/time-zones/releases/tzdata1999b.tar.gz";
      sha256 = "d18af887eac875bd97b10efa4dee2a3eeb80a1881c50818db34a73b37ff330a2";
    }];
    "38701498edf08394fb51ef22ef99351fde1de871" = [{
      name = "tzdata2014i";
      url = "https://data.iana.org/time-zones/releases/tzdata2014i.tar.gz";
      sha256 = "2af331bdd2b794ec59b8ded7300fb29dc3573a009ec14183f5c9ad38e3886153";
    }];
    "e224dead63f2362679e775cc8c9c92e41d8c8ada" = [{
      name = "tzdata2009d";
      url = "https://data.iana.org/time-zones/releases/tzdata2009d.tar.gz";
      sha256 = "f884ff8af90824cac55786e4b3a6048af10702a5f15036bf55f33d74704ad102";
    }];
    "0098bd8f0a47871e728d40fca476b7c42f988894" = [{
      name = "tzdata96c";
      url = "https://data.iana.org/time-zones/releases/tzdata96c.tar.gz";
      sha256 = "3edcf59c3f79acb3035777348c8fdccf14786cf50f0e085035965d0945226660";
    }];
    "33143e05ac18f5c2618df3b30ade30b488ecbc83" = [{
      name = "tzdata96i";
      url = "https://data.iana.org/time-zones/releases/tzdata96i.tar.gz";
      sha256 = "8a26fd4aa3e7bf474f1d51be394e309737fb2c157dc8014cfcf2a5a3f4084289";
    }];
    "ab0e8405a16af3653a5610979ab2a7392ec4fbba" = [{
      name = "tzdata95h";
      url = "https://data.iana.org/time-zones/releases/tzdata95h.tar.gz";
      sha256 = "f098b4cbfdaaa016fd324749997b0768ca6e92b36444bb64d11d765b23ab4ae6";
    }];
    "b2a758d41cee560ab9778e8978910661d637a6eb" = [{
      name = "tzdata1997j";
      url = "https://data.iana.org/time-zones/releases/tzdata1997j.tar.gz";
      sha256 = "7d5a15ec86a40cc8c1718301753602d828121b9b19c3a4627bf53b004dd7a7e9";
    }];
    "d319f5cd4b83cb39e07982e57ec8fa0187c693f8" = [{
      name = "tzdata2017b";
      url = "https://data.iana.org/time-zones/releases/tzdata2017b.tar.gz";
      sha256 = "f8242a522ea3496b0ce4ff4f2e75a049178da21001a08b8e666d8cbe07d18086";
    }];
    "a6c3d71f651ce2bbb77391993c8bec4bb6ce8410" = [{
      name = "tzdata2013a";
      url = "https://data.iana.org/time-zones/releases/tzdata2013a.tar.gz";
      sha256 = "ed9f273f52d5df9ec09fdcf6684176bbdc86d0fbafcbc27b97e5a9c103024afc";
    }];
    "1d5fd8d6bfe79b8a5678e3890a3171dc7e9290d8" = [{
      name = "tzdata2015c";
      url = "https://data.iana.org/time-zones/releases/tzdata2015c.tar.gz";
      sha256 = "860fac5f5f57f7a2dfc1ba682dbd1f5c0f0b597f761571277b6ed6561e22365a";
    }];
    "8c53ae59c082b63c7ed0261ac99eb2bd30675aa4" = [{
      name = "tzdata2004d";
      url = "https://data.iana.org/time-zones/releases/tzdata2004d.tar.gz";
      sha256 = "5f29f06a404cfc437402b54cff64158c7cd1af81f97101fc6b516a51ab3ea206";
    }];
    "463561ed73c004096d46613a9c94af2b635c4ebf" = [{
      name = "tzdata96h";
      url = "https://data.iana.org/time-zones/releases/tzdata96h.tar.gz";
      sha256 = "8264544985aaf12ff20ea14d963e361c4422ce8fd5bd8c69b92ec0e296f4fe32";
    }];
    "232ead96202bafd93c01c3ecc7d3304ab560105d" = [{
      name = "tzdata1999e";
      url = "https://data.iana.org/time-zones/releases/tzdata1999e.tar.gz";
      sha256 = "d1189cc273a655081891bf7a92103cf394015511033f8eb239acba6fdf453aa4";
    }];
    "b15518ce5eb429242908ee274a56bec03281f62b" = [{
      name = "tzdata2019c";
      url = "https://data.iana.org/time-zones/releases/tzdata2019c.tar.gz";
      sha256 = "79c7806dab09072308da0e3d22c37d3b245015a591891ea147d3b133b60ffc7c";
    }];
    "31f27c304b7716bc02791ccdfa7e565bac220ac0" = [{
      name = "tzdata2013b";
      url = "https://data.iana.org/time-zones/releases/tzdata2013b.tar.gz";
      sha256 = "70d589d0e76a3749403d2bb404e9214c2520dda4c13e4b07b1b945ed2c64edb2";
    }];
    "38ba2b6de800879f0c0e9da98e724422ff381738" = [{
      name = "tzdata2013d";
      url = "https://data.iana.org/time-zones/releases/tzdata2013d.tar.gz";
      sha256 = "cd1c96f0676e0edceebc6a418a2222ffb05becb41180dd9f847b9c7cef303b04";
    }];
    "37d16a3196381ddb48cfcad7ebbeeaa24092f79e" = [{
      name = "tzdata2014g";
      url = "https://data.iana.org/time-zones/releases/tzdata2014g.tar.gz";
      sha256 = "5547d5b7a982f7f53fffe68cb2a13692553f591a17d58c8ef15b20679d82a270";
    }];
    "d34c0c6aeb16e0a4e1b4b06573459df0f4c86122" = [{
      name = "tzdata96e";
      url = "https://data.iana.org/time-zones/releases/tzdata96e.tar.gz";
      sha256 = "1751e9dd15dfec61d9702920b4c3d4be42aa9964a5b8cce2b369854a1263d7b3";
    }];
    "853437e5ce5056745b00375a26a2a34d843acae0" = [{
      name = "tzdata2010j";
      url = "https://data.iana.org/time-zones/releases/tzdata2010j.tar.gz";
      sha256 = "dcf2101d0c5bb20a7f182866ea3e52b54c8f4d129c025a96c9a31377676f554b";
    }];
    "12b5d2c7390549c88eb48c7d5ebbaa99144bd869" = [{
      name = "tzdata2013f";
      url = "https://data.iana.org/time-zones/releases/tzdata2013f.tar.gz";
      sha256 = "5b72ed29bea75e0b59cbd3f575db0aac62f96a2a36e652725f674a92a95d4ada";
    }];
    "d92d3e2b8cd9c1973d30d9b1a35d6888d23a03c3" = [{
      name = "tzdata2004g";
      url = "https://data.iana.org/time-zones/releases/tzdata2004g.tar.gz";
      sha256 = "950efec3d662b31f617cf79cc6d99ffe84f2269f8ba9a892aa5c0662a51adcfc";
    } {
      name = "tzdata2005a";
      url = "https://data.iana.org/time-zones/releases/tzdata2005a.tar.gz";
      sha256 = "5157c42015c8068068a8510c0f9dc07586169ee5a8fc99c691783126fe3b42c1";
    }];
    "fad57e12815a91684070858d9c34edc58a952846" = [{
      name = "tzdata2008i";
      url = "https://data.iana.org/time-zones/releases/tzdata2008i.tar.gz";
      sha256 = "ec8824897cc79308b4ec6946a049d4680539e8de9c764b592bcf126f9060d7af";
    }];
    "6969154dde2c75adacf99c64af0ad8292b35fca5" = [{
      name = "tzdata2006p";
      url = "https://data.iana.org/time-zones/releases/tzdata2006p.tar.gz";
      sha256 = "6b246374b468d8ead477541f4624b74cd1da2b3de7ef757a3fc40ca29cfb29bc";
    }];
    "d056209a6744485ca649acc277f674448a886ad1" = [{
      name = "tzdata2018b";
      url = "https://data.iana.org/time-zones/releases/tzdata2018b.tar.gz";
      sha256 = "f87540b9050e1b0d772d19058fcb62f54baa505ecebf392ea825713c33bd9848";
    }];
    "f52ac2309b28b8d79776bbc014c63b9501a4caac" = [{
      name = "tzdata2011j";
      url = "https://data.iana.org/time-zones/releases/tzdata2011j.tar.gz";
      sha256 = "7e8540a85f1b474df1b40b403bea5748311ca7731b3038e51d6abc7f2d223c2a";
    }];
    "d979d12f0912737480e554e2915459b905220779" = [{
      name = "tzdata96a";
      url = "https://data.iana.org/time-zones/releases/tzdata96a.tar.gz";
      sha256 = "d5170a362e7409fa7174042ee5cb4efa40a60c70ce36834969493cda46bc463e";
    }];
    "3c40cfdb415c547de15eba0498d960715cfefe37" = [{
      name = "tzdata2014d";
      url = "https://data.iana.org/time-zones/releases/tzdata2014d.tar.gz";
      sha256 = "4b4966912f5d4a299b0bdf47e6f3103d82dc6a0b5a6b321e2b9d5662597a62f0";
    }];
    "214e8413b5da90d6e5d9f6d916be43b48a9f0669" = [{
      name = "tzdata96b";
      url = "https://data.iana.org/time-zones/releases/tzdata96b.tar.gz";
      sha256 = "af6f0b66475d977a4040f73e31ae83186501020b0e54418d3b826cb0252f9321";
    }];
    "dc0ced3040dcbc03630e65d2417945b814cb1608" = [{
      name = "tzdata2011k";
      url = "https://data.iana.org/time-zones/releases/tzdata2011k.tar.gz";
      sha256 = "51f7d2a42b7fb9465feced642a6676afdf8b04a071e55f3fef1f0925bd67ef21";
    }];
    "db72b938d2cfb3fe354af8f6842300c8d6208da6" = [{
      name = "tzdata1998a";
      url = "https://data.iana.org/time-zones/releases/tzdata1998a.tar.gz";
      sha256 = "066479d0da15f3fbf82d40e6b3f0043a8ae6aa18dab3170724e2ea1aa1003b4e";
    }];
    "95cf198cf7786b9bd01c473acef97a83df3c568f" = [{
      name = "tzdata1998h";
      url = "https://data.iana.org/time-zones/releases/tzdata1998h.tar.gz";
      sha256 = "860728777a740bba36afff8eb5fffb00eec289308786c6e03af6d61c2036def7";
    }];
    "7960910282bef13f94763d0c9782c6a905297f0f" = [{
      name = "tzdata96k";
      url = "https://data.iana.org/time-zones/releases/tzdata96k.tar.gz";
      sha256 = "02f8321a3236105338a2a071f9f9ef98dadeb8f939cbe3dc2dd53e1931015604";
    }];
    "a7192b7b16d072863839ee24cc68cb944f942fa4" = [{
      name = "tzdata94h";
      url = "https://data.iana.org/time-zones/releases/tzdata94h.tar.gz";
      sha256 = "0df84818543f53783a6c7aa839bffd4cfbb3efccf441003b2cb1889869d2fedd";
    }];
    "503e142d64b2c092828af30571e8528044c2bb7e" = [{
      name = "tzdata2009c";
      url = "https://data.iana.org/time-zones/releases/tzdata2009c.tar.gz";
      sha256 = "3dd1bd0014e7c9a74cab9a21fd32c9cadd30b2c69340f32a685e7b52207c1db8";
    }];
    "ff665b96f7d50272d0a8e0e321d530c8b09380a5" = [{
      name = "tzdata94b";
      url = "https://data.iana.org/time-zones/releases/tzdata94b.tar.gz";
      sha256 = "4357581dc85487bcb59a7141d4ed5ee742e4ecccc2da7684d7f168751c61fc18";
    }];
    "b39d2ae205385ad6124a82d15e772741dc63585f" = [{
      name = "tzdata2012d";
      url = "https://data.iana.org/time-zones/releases/tzdata2012d.tar.gz";
      sha256 = "46c0e92a7aa89c3cfe571b585ceb6958bb444604aea3e09587f2cbe474c95575";
    }];
    "f8f8bfa1687b4698005cd64db1ff57ae21b17261" = [{
      name = "tzdata2006a";
      url = "https://data.iana.org/time-zones/releases/tzdata2006a.tar.gz";
      sha256 = "76c5d3b373c8f65968fd6e7bb2222fb0f0e33ef1a58c519527aa68c537d2b448";
    }];
    "0ec11f957dd8a61142f48e15f13a063490c04484" = [{
      name = "tzdata2010d";
      url = "https://data.iana.org/time-zones/releases/tzdata2010d.tar.gz";
      sha256 = "c18916b1e0d91dd7a0f8a26a570e40db06bdd0dc06cf8d66c06f78704d8b3b78";
    }];
    "1c85fdc740aef2bf4d24e327a4b1168736b56c0d" = [{
      name = "tzdata2006b";
      url = "https://data.iana.org/time-zones/releases/tzdata2006b.tar.gz";
      sha256 = "aab3cf0e8c9db27df345571e224d04ed0cd7e41399bd59dd3db20d9c3b45beb2";
    }];
    "d1e51661456d09635672072e7247985c134bfe4f" = [{
      name = "tzdata2006n";
      url = "https://data.iana.org/time-zones/releases/tzdata2006n.tar.gz";
      sha256 = "406896398bb307eea317758790f320e3d5f2c61eceb7442ec1461c7bfcd66a60";
    }];
    "c6fb0ae3f5d8e2684cf3635222e3b636fc324cd1" = [{
      name = "tzdata2008a";
      url = "https://data.iana.org/time-zones/releases/tzdata2008a.tar.gz";
      sha256 = "104a270bdc7a511cffd41d2722ff3fafd0caf221b4344263316177e8a64abbf1";
    }];
    "7140f27bd72fd97f927b666a6188c42b478c993a" = [{
      name = "tzdata2012i";
      url = "https://data.iana.org/time-zones/releases/tzdata2012i.tar.gz";
      sha256 = "c9e5b6b6a2031236126409b3595cd8e1a730febc1e8b3802fdbdb417977cf162";
    }];
    "4641d762bdfd45005ffe23a21bace16fb2e5c50a" = [{
      name = "tzdata95k";
      url = "https://data.iana.org/time-zones/releases/tzdata95k.tar.gz";
      sha256 = "668316a70eb8cc1a8ed0a2ebd9b1e34bd4ec3eb9bcb3ad068b1cc6e4812d1caf";
    }];
    "c29930b9aa9daf238f29ff3e4c0c034cb8d79e8d" = [{
      name = "tzdata2003d";
      url = "https://data.iana.org/time-zones/releases/tzdata2003d.tar.gz";
      sha256 = "6f9eb3f50ac114994a50ceb411d8e064514b3ebd7b2d25eff703ae4be4e8ea88";
    }];
    "4ae48399d3ffcceddbbe0e364dac9fc3b8e7fd36" = [{
      name = "tzdata2000e";
      url = "https://data.iana.org/time-zones/releases/tzdata2000e.tar.gz";
      sha256 = "a121d69fd837a0e99b0b807d0b5de447344b7660011bdbdc0b8d6ba6ed81b26f";
    }];
    "be3ff7820ca5dd17ec538d074385134387ffff23" = [{
      name = "tzdata2019a";
      url = "https://data.iana.org/time-zones/releases/tzdata2019a.tar.gz";
      sha256 = "90366ddf4aa03e37a16cd49255af77f801822310b213f195e2206ead48c59772";
    }];
    "555a8eac2d62bb7816bd20dfedccd91d748e587f" = [{
      name = "tzdata2011c";
      url = "https://data.iana.org/time-zones/releases/tzdata2011c.tar.gz";
      sha256 = "c08fbf767280a6f6dc450306a39d3b5818a0a9792a0991320e00a1bb91e91a3b";
    }];
    "d18f39d3c92f216c3229f733572c72a87778b74c" = [{
      name = "tzdata1997f";
      url = "https://data.iana.org/time-zones/releases/tzdata1997f.tar.gz";
      sha256 = "8e127212db36db93d4e5a4b87f3af96b549d1b3da49a1b6d61dd21456420892a";
    }];
    "e4216ad2e271c770f21e3e3c035a1814c2117779" = [{
      name = "tzdata2012j";
      url = "https://data.iana.org/time-zones/releases/tzdata2012j.tar.gz";
      sha256 = "4b6a3c2831bdbb68ab1a1bf906bcf11d18ab78009713a0339da6fe96b6afceaa";
    }];
    "d07b6f4c96583b520c598c2ec642997456bc7a31" = [{
      name = "tzdata2016j";
      url = "https://data.iana.org/time-zones/releases/tzdata2016j.tar.gz";
      sha256 = "f5ee4e0f115f6c2faee1c4b16193a97338cbd1b503f2cea6c5a768c82ff39dc8";
    }];
    "64afaaed2b88c38a29f9fb4198f22662323d3ceb" = [{
      name = "tzdata95l";
      url = "https://data.iana.org/time-zones/releases/tzdata95l.tar.gz";
      sha256 = "f9c82e19c5837e737f59c1d6f61352e7d1ca5178839124a313b78f593254a80b";
    }];
    "191a315cdfccae9f67c584f39c7341182fef2d7d" = [{
      name = "tzdata1997c";
      url = "https://data.iana.org/time-zones/releases/tzdata1997c.tar.gz";
      sha256 = "ed75b22a4c854aef3d4523716523b37d79596527bc3fa6264297ec0964c886f1";
    } {
      name = "tzdata1997d";
      url = "https://data.iana.org/time-zones/releases/tzdata1997d.tar.gz";
      sha256 = "05733d47c02b294dc13501c34e7bd5dc7ab8065a9e62381994c6bc1c458a0e46";
    }];
    "96f3d0c18031ba923b5599815aa55b96aa563a56" = [{
      name = "tzdata1997a";
      url = "https://data.iana.org/time-zones/releases/tzdata1997a.tar.gz";
      sha256 = "5713250de4af5a0c17e2df3db754b3dd9857be64f33ba0eab9c9a7b7c0ed1624";
    }];
    "71a35d7b783a5e821aedb72fd77c8d7557ed9475" = [{
      name = "tzdata2001b";
      url = "https://data.iana.org/time-zones/releases/tzdata2001b.tar.gz";
      sha256 = "9ec6c36fe2af023f58938f83e3ffb7d489fb4447e2cd52917557761bcdeb6784";
    }];
    "db6d3129149358ce6fde1c1a642a06b1ec5ddf61" = [{
      name = "tzdata2009m";
      url = "https://data.iana.org/time-zones/releases/tzdata2009m.tar.gz";
      sha256 = "7609980204940ceaf74b5a48d15ea0c079eaec627e149cf3d986cfed268881fe";
    }];
    "c2195a5dcf2c70dba634c35a008ef300508cb6e7" = [{
      name = "tzdata2007j";
      url = "https://data.iana.org/time-zones/releases/tzdata2007j.tar.gz";
      sha256 = "0319a3dc08f05a92b5c409cc7278a45fa6194bcdfdd27918554bd3d8d6d33c6d";
    }];
    "95e97c9112af6c4a00e6eb2c12ed0009d4a8b815" = [{
      name = "tzdata2014c";
      url = "https://data.iana.org/time-zones/releases/tzdata2014c.tar.gz";
      sha256 = "aa2924e012644de3a6cc3160ffff690cb3afecf350af435daefa43bb669fb8f1";
    }];
    "4d36dca233d62c44e861af9ee674e4f785b2e046" = [{
      name = "tzdata2011a";
      url = "https://data.iana.org/time-zones/releases/tzdata2011a.tar.gz";
      sha256 = "782c691b4750bdefeb84063128db685a8b8f31dc2efb887ee841ae105bfa747b";
    }];
    "8e14c1bd3ded226a2085d8be6e93e08cc61f236e" = [{
      name = "tzdata2014h";
      url = "https://data.iana.org/time-zones/releases/tzdata2014h.tar.gz";
      sha256 = "e78152f616fb07c1dea124215ffca57d0de66d8897e00896086542e3de30f69e";
    }];
    "7ee09e55cb1d3e25074e98beb83d2b3c1f59a4a5" = [{
      name = "tzdata2020a";
      url = "https://data.iana.org/time-zones/releases/tzdata2020a.tar.gz";
      sha256 = "547161eca24d344e0b5f96aff6a76b454da295dc14ed4ca50c2355043fb899a2";
    }];
    "c5160ae03e3834688c95ea50253221648ffa93c0" = [{
      name = "tzdata2018h";
      url = "https://data.iana.org/time-zones/releases/tzdata2018h.tar.gz";
      sha256 = "b8cbcf3e46aed30ad27c40d5bed68c16cf759384d14cc6411b84460c88bdd91f";
    }];
    "97790ee1282b4a87ba73c6fccacce8d3e652e5eb" = [{
      name = "tzdata2012h";
      url = "https://data.iana.org/time-zones/releases/tzdata2012h.tar.gz";
      sha256 = "65e53218eff4f71f8e7eaa0ae52aecec79e0ba186bd5badc27c099118d4cd065";
    }];
    "6118d6f353572bf308cbdef2cd0a6b7bd29fcc26" = [{
      name = "tzdata2006c";
      url = "https://data.iana.org/time-zones/releases/tzdata2006c.tar.gz";
      sha256 = "54f07a727eff281cebd7d997726584207eb6bfbf8080f9b32f085963b1070aa1";
    }];
    "0c104e1a84371860973049404d9550eaea1ec363" = [{
      name = "tzdata2002b";
      url = "https://data.iana.org/time-zones/releases/tzdata2002b.tar.gz";
      sha256 = "d1a9d1c36b1d08745d405cf2e5ed4c7224093a8d53f141b90d5bed5641f5e59d";
    }];
    "741520f19d9ddc703d3456de6f51564110d02e4a" = [{
      name = "tzdata2017c";
      url = "https://data.iana.org/time-zones/releases/tzdata2017c.tar.gz";
      sha256 = "d6543f92a929826318e2f44ff3a7611ce5f565a43e10250b42599d0ba4cbd90b";
    }];
    "0dd8db7853a6f776b478e465ac45bca646278245" = [{
      name = "tzdata2005o";
      url = "https://data.iana.org/time-zones/releases/tzdata2005o.tar.gz";
      sha256 = "f8dc475e443e259e9f69b65523974338dee4393c8d73779847c2cc49261c6933";
    }];
    "4a92eadfac2fe62912d0772769d0ef38d8ef4923" = [{
      name = "tzdata2011h";
      url = "https://data.iana.org/time-zones/releases/tzdata2011h.tar.gz";
      sha256 = "c098786d053736dd18d4f1fbebdf41554c6fd702a36f75c18f1c66712d2abc24";
    }];
    "835e88b3b0a560e79dfc0a2a6c350adeaa4ef907" = [{
      name = "tzdata1996l";
      url = "https://data.iana.org/time-zones/releases/tzdata1996l.tar.gz";
      sha256 = "623a48745864731e7ecb4d97d9174b3e0e856a1c25d79cd5fb64942cf282d3e1";
    }];
    "d81a8327ecf60f04c5b0b2e052d7b8088ceb31fb" = [{
      name = "tzdata2005m";
      url = "https://data.iana.org/time-zones/releases/tzdata2005m.tar.gz";
      sha256 = "406a84f30884e6dcbbdb827152216e7a6d1284fb118d7cf4498c998575dd9339";
    }];
    "ec27ba702b29ecb10abba5ad02b936da38eb8640" = [{
      name = "tzdata2008f";
      url = "https://data.iana.org/time-zones/releases/tzdata2008f.tar.gz";
      sha256 = "81e0d0d86acd072f233a7ac9413f95f147ac64355e3d09708c228af115c05678";
    }];
    "811a74dcd49f53216561231bce077a63467251ae" = [{
      name = "tzdata2018d";
      url = "https://data.iana.org/time-zones/releases/tzdata2018d.tar.gz";
      sha256 = "5106eddceb5f1ae3a91dbd3960e1b8b11ba0dc08579a31cf0724a7691b10c054";
    }];
    "43f3b86f92af2ba91b6442bce417feb05c9ede85" = [{
      name = "tzdata2008b";
      url = "https://data.iana.org/time-zones/releases/tzdata2008b.tar.gz";
      sha256 = "633d76612d73a7add41a3b90fe5721ea5f4282d52bd8408b9d4fab261443aa6c";
    }];
    "7fc663380f8c8e80136786da7239a9c5cac6c774" = [{
      name = "tzdata2008g";
      url = "https://data.iana.org/time-zones/releases/tzdata2008g.tar.gz";
      sha256 = "78a90cf70e9cd661ba253236b558216d2f707f3457b20a05e7ede04ab5acf0b6";
    }];
    "6b5d95e7e14d78660dd6daceeb134147ae281ba1" = [{
      name = "tzdata2007f";
      url = "https://data.iana.org/time-zones/releases/tzdata2007f.tar.gz";
      sha256 = "cfedfd49351d41da0fe5a26be2eadc8ae0cf1b5b1cea1d31aafb6913f907493e";
    }];
    "b4d095b8742cd706d4b4d4025f28462c82d68067" = [{
      name = "tzdata1999c";
      url = "https://data.iana.org/time-zones/releases/tzdata1999c.tar.gz";
      sha256 = "7d3f04a9a6ed8e1ad2a214990c8e499b40e914f744a10a2e0bb508624da51f73";
    }];
    "7007a0cd1a2193c994245082bf54cf50533e7d17" = [{
      name = "tzdata2004a";
      url = "https://data.iana.org/time-zones/releases/tzdata2004a.tar.gz";
      sha256 = "ad07c4ab84ea8c87aa07220d421d02d95fd14e2a8de5e78f443949fe992886e3";
    }];
    "6f0e322b00c80197a3477b47397955e94a0ad5c0" = [{
      name = "tzdata2007a";
      url = "https://data.iana.org/time-zones/releases/tzdata2007a.tar.gz";
      sha256 = "7866826c0fd0810af2bb2b240c81961b0350c1fa42db870baa33c6126039e0d3";
    }];
    "505173c636d3daf410d3efcf5466d2080f40d187" = [{
      name = "tzdata2003a";
      url = "https://data.iana.org/time-zones/releases/tzdata2003a.tar.gz";
      sha256 = "d804af81f58ece4b13700f7b59f970354a213d82f010349d4b3146ad5a0b864e";
    }];
    "5700a4ad8ec7d43962914e568bf7bcf603b90ea5" = [{
      name = "tzdata2010b";
      url = "https://data.iana.org/time-zones/releases/tzdata2010b.tar.gz";
      sha256 = "a93208ae389cc0d3618731cc9f406ba2cfc6aac39668a06c687d3fae2a7e8210";
    }];
    "2ed0eb26e4a2af5633cb0bc731ae163c9fab28f2" = [{
      name = "tzdata1998e";
      url = "https://data.iana.org/time-zones/releases/tzdata1998e.tar.gz";
      sha256 = "8bdd9ae68bc39cb2bcae6bdc338225f31d548413c9f656856f97a6f1c885e289";
    }];
    "f46add2b96b8f014435d278ae0ee0c1827c5e3f9" = [{
      name = "tzdata2019b";
      url = "https://data.iana.org/time-zones/releases/tzdata2019b.tar.gz";
      sha256 = "05d9092c90dcf9ec4f3ccfdea80c7dcea5e882b3b105c3422da172aaa9a50c64";
    }];
    "de5b0c31b9056c42615c16d103d7e248fe3f2a9f" = [{
      name = "tzdata2016c";
      url = "https://data.iana.org/time-zones/releases/tzdata2016c.tar.gz";
      sha256 = "8700d981e6f2007ac037dabb5d2b12f390e8629bbc30e564bc21cf0c069a2d48";
    }];
    "2b5b3816ec686a63e6755db6611fa87d90bd8345" = [{
      name = "tzdata2015f";
      url = "https://data.iana.org/time-zones/releases/tzdata2015f.tar.gz";
      sha256 = "959f81b541e042ecb13c50097d264ae92ff03a57979c478dbcf24d5da242531d";
    }];
    "f2b45547673a59012429b67701a2eb1de7d3feaf" = [{
      name = "tzdata2010c";
      url = "https://data.iana.org/time-zones/releases/tzdata2010c.tar.gz";
      sha256 = "e5fa92874b6f051166cf2fc2dced0dea165c4d7508a173ea6d232bdee7e05201";
    }];
    "43b1e749971f5fa0a1fb39161c35f7825a368aed" = [{
      name = "tzdata2008c";
      url = "https://data.iana.org/time-zones/releases/tzdata2008c.tar.gz";
      sha256 = "ae32f514a57bbd4d8ff5ec280aa0eb7c27cb6c8c9a9167a1397e6788900cb41b";
    }];
    "09eb5721b745bbc8021d64fe7d70ddfaa2871067" = [{
      name = "tzdata2009b";
      url = "https://data.iana.org/time-zones/releases/tzdata2009b.tar.gz";
      sha256 = "f2c4e8f816a1e15c46ec78e23fcbe18d559e925cc2c99799243e5a749b2a8c68";
    }];
    "f170492ed2f8ba4dd32185720ee2f5b91af781c2" = [{
      name = "tzdata2014f";
      url = "https://data.iana.org/time-zones/releases/tzdata2014f.tar.gz";
      sha256 = "eed690a72124f380bcb14947d398a7a482acb9ab792ae78bd4554e52c5ca2001";
    }];
    "e36937a9d04159b13130710c56e98f7ca47e3e93" = [{
      name = "tzdata2000d";
      url = "https://data.iana.org/time-zones/releases/tzdata2000d.tar.gz";
      sha256 = "287f1e87957cc79d6f8cfb085473ef147a338621b486b346d819b681d0f03365";
    }];
    "c0241ac58a3d4615d3cc20c0825323ab03781983" = [{
      name = "tzdata1999j";
      url = "https://data.iana.org/time-zones/releases/tzdata1999j.tar.gz";
      sha256 = "4b3c7b2146bf247fbc3287f55fddc48b372b2b8e9b981e39dede047dbd6f20bc";
    }];
    "d81472e3667e5b97ec190a015ba78c69d5155dd3" = [{
      name = "tzdata2009j";
      url = "https://data.iana.org/time-zones/releases/tzdata2009j.tar.gz";
      sha256 = "ab6fb5b3588208ab0cade05dfa8d6ef9516bc719613a0676137e56c336cb7bb7";
    }];
    "3c7318fb6f8b54dbd0b536cf8341a9367174e6e8" = [{
      name = "tzdata2005n";
      url = "https://data.iana.org/time-zones/releases/tzdata2005n.tar.gz";
      sha256 = "3a9d172a56f6535f1361f972bbba9228f83e4f5ab594b43ef0df09bef1df8302";
    }];
    "35d2496619ee14a17f269fd0fb9a4c14a5ebc746" = [{
      name = "tzdata2009s";
      url = "https://data.iana.org/time-zones/releases/tzdata2009s.tar.gz";
      sha256 = "ee9000a0276675ed697f8d404edf80104fd338c3fb979907e4ee63ca83d65e5e";
    }];
    "41cf88f7b28ae614dfe8e4cf2d0f976cdf5cadbe" = [{
      name = "tzdata2002d";
      url = "https://data.iana.org/time-zones/releases/tzdata2002d.tar.gz";
      sha256 = "357cebd44837bc255e01f65072325b26590b3d4c7abb3e850a21e2ee18699a57";
    }];
    "ae31d90cddd593a1e9d8e9416c19a4235ff520ad" = [{
      name = "tzdata2016a";
      url = "https://data.iana.org/time-zones/releases/tzdata2016a.tar.gz";
      sha256 = "5efa6b324e64ef921ef700ac3273a51895f672684a30e342f68e47871c6a8cd1";
    }];
    "5cee98fd13b7cc03af48b926534759f515d2c1b6" = [{
      name = "tzdata95b";
      url = "https://data.iana.org/time-zones/releases/tzdata95b.tar.gz";
      sha256 = "f0e65427d2e88a11d499ac0e0cfe19cb508c17aebcacf2b60428f07510a241f8";
    }];
    "2bb1cab747342b51710b417290dade36b7c2f752" = [{
      name = "tzdata2001d";
      url = "https://data.iana.org/time-zones/releases/tzdata2001d.tar.gz";
      sha256 = "ef1b55d0d611a4be164d1209013fff6727cddc1fde858ebb6dcd3f903760b62e";
    }];
    "4dc1e88d7a3760cc96bc9c4757b925df83ac47d7" = [{
      name = "tzdata2000h";
      url = "https://data.iana.org/time-zones/releases/tzdata2000h.tar.gz";
      sha256 = "b69cdac96691679157077fbd375c50588e25e8f0bb0a5d6c942ae8e8745baacf";
    }];
    "65cd4ceb082560b20fc03b165459297322077ff9" = [{
      name = "tzdata2018f";
      url = "https://data.iana.org/time-zones/releases/tzdata2018f.tar.gz";
      sha256 = "0af6a85fc4ea95832f76524f35696a61abb3992fd3f8db33e5a1f95653e043f2";
    }];
    "0496f08c097b93e8acf041198aa5c1e9a20409c8" = [{
      name = "tzdata2014b";
      url = "https://data.iana.org/time-zones/releases/tzdata2014b.tar.gz";
      sha256 = "d1e1f3e0c253a8ac0b35ffe27ef95f6366c37beb953391806cd922efce2b1cb5";
    }];
    "9019d1e894cfddcb8aa3ff37592320941d743e10" = [{
      name = "tzdata2003b";
      url = "https://data.iana.org/time-zones/releases/tzdata2003b.tar.gz";
      sha256 = "d62280b493eaabd094c69b92dbbc4e62432310e71d90965597959cbce11e2c1b";
    } {
      name = "tzdata2003c";
      url = "https://data.iana.org/time-zones/releases/tzdata2003c.tar.gz";
      sha256 = "aeb4aa79d15d5b4a4dc56f4e16ac2991188edca7046be78e497c082f0b5a1770";
    }];
    "3dfbdb3d218c10d26dcdd381f846b26f9f728fab" = [{
      name = "tzdata2013e";
      url = "https://data.iana.org/time-zones/releases/tzdata2013e.tar.gz";
      sha256 = "d02891fbcca61d527263e9250b8cef2c93396ca05cd723832f04fe79e4058d97";
    }];
    "9759fc435e0fed2e5b6dc65e34da0ab5a6406711" = [{
      name = "tzdata2012a";
      url = "https://data.iana.org/time-zones/releases/tzdata2012a.tar.gz";
      sha256 = "c28f731e19e7b612e26b2a41e9089ebe0c67bad422d2b7882e4b32983277ee7d";
    }];
    "127445424481c738a13513ec8416ae4d9f8e89db" = [{
      name = "tzdata1999h";
      url = "https://data.iana.org/time-zones/releases/tzdata1999h.tar.gz";
      sha256 = "073e16f4bfcf2f4b8a142b4daca8e538448e3f2db4f9cf899c23e1e425337c6c";
    }];
    "c3abe4165d88d36b015eb341b65ff5c5a4c98bf4" = [{
      name = "tzdata96d";
      url = "https://data.iana.org/time-zones/releases/tzdata96d.tar.gz";
      sha256 = "afc72ab3d82056409328e84c36a0fbbea9015a4f2733e7666b84bd63c5f5baf0";
    }];
    "9a48f5c5461744bc122cc7f8fa12a5f9c28a13f8" = [{
      name = "tzdata2009q";
      url = "https://data.iana.org/time-zones/releases/tzdata2009q.tar.gz";
      sha256 = "5ea1abc8b08dd7f67b53488a497d61f9617ed92d094e508e103049430518a19a";
    }];
    "bd903db705630d9671a37262d344f54ac5acf12f" = [{
      name = "tzdata1998b";
      url = "https://data.iana.org/time-zones/releases/tzdata1998b.tar.gz";
      sha256 = "4313a44490b8ec8e5cd20742ce39306cd363622583fcc624c4fbf3f7719df7e4";
    }];
    "76dd3d064778ea8b569151e04193916946001e94" = [{
      name = "tzdata2015e";
      url = "https://data.iana.org/time-zones/releases/tzdata2015e.tar.gz";
      sha256 = "ffc9b5d38abda8277aa479e3f75aa7668819d0977cd1a0c8ef3b09128334ba6f";
    }];
    "26b5a67abaf0279400cea663658bc776ef880d6d" = [{
      name = "tzdata2008e";
      url = "https://data.iana.org/time-zones/releases/tzdata2008e.tar.gz";
      sha256 = "ddd526edfaf0d43fbe8facf772feb13266ae3cdddaf69a612b7a74cf37036548";
    }];
    "e23f9c1832e5312c899a2e1f2741ef5c02b6473b" = [{
      name = "tzdata2016g";
      url = "https://data.iana.org/time-zones/releases/tzdata2016g.tar.gz";
      sha256 = "3c7137b2bc47323b0de47b77786bacf81ed503d4b2c693ff8ada2fbd1281ebd1";
    }];
    "b049e5ca923113cf5fbd59acb9e10ef78173735f" = [{
      name = "tzdata2009r";
      url = "https://data.iana.org/time-zones/releases/tzdata2009r.tar.gz";
      sha256 = "684d23e3ebe825c9db90732534446f4e33f5ad4455980b15fd9eb2e4ba5a6731";
    }];
    "335980e19adeb026ab139b51b593d4e75312346d" = [{
      name = "tzdata2012g";
      url = "https://data.iana.org/time-zones/releases/tzdata2012g.tar.gz";
      sha256 = "9a82e74f798d69c18b48e0128c46b6ea10132d9495cbcc4105e7483150a85bac";
    }];
    "711ec1643b290c625cab8697f2716d7633830ff5" = [{
      name = "tzdata2010h";
      url = "https://data.iana.org/time-zones/releases/tzdata2010h.tar.gz";
      sha256 = "a4918d60f63440ba9b6050205881e8a98d718dc0c2b7df5955f43e781eab6e7d";
    }];
    "716574d218db2328a3059ba79f179695ef77fcda" = [{
      name = "tzdata2015b";
      url = "https://data.iana.org/time-zones/releases/tzdata2015b.tar.gz";
      sha256 = "556ac1a5b3a371adc1ad4e77138f78ddd7f8ddd7bc2b52545924598c7dc8ad62";
    }];
    "d5506bf9dc54bddf87ce34e54075f1bdb8e1e01c" = [{
      name = "tzdata95i";
      url = "https://data.iana.org/time-zones/releases/tzdata95i.tar.gz";
      sha256 = "473d5caabf161135321e6b783f8d42e799af56c8ee66618d64fd3165c72c8a51";
    }];
    "7c99b04697ed5d56d11cbc10f8fecfaa3a385d4e" = [{
      name = "tzdata2000f";
      url = "https://data.iana.org/time-zones/releases/tzdata2000f.tar.gz";
      sha256 = "c70b89795dd46b06cf16f3bd19f85f817173d3964478b680fbcf956ee32d928c";
    }];
    "ba2f93c0ab0060979f7a0ad4a9bad6cbf84cd091" = [{
      name = "tzdata2010k";
      url = "https://data.iana.org/time-zones/releases/tzdata2010k.tar.gz";
      sha256 = "ef69c99504c0fd9864ba8ef1daae5f2d4df097cf7dc350f09b8f70386272408d";
    }];
    "fa03174c614d5ad1c2a53450da004d2e12294c8a" = [{
      name = "tzdata2011e";
      url = "https://data.iana.org/time-zones/releases/tzdata2011e.tar.gz";
      sha256 = "44fef01de4589a4979eb6b5fdbbfd21a3b135852af1ecbfb9e0368ae47392c79";
    }];
    "febe69ddec72e7040ebe21fa643f05e01b1661d8" = [{
      name = "tzdata2012e";
      url = "https://data.iana.org/time-zones/releases/tzdata2012e.tar.gz";
      sha256 = "061c1c289e792f3661135d5ec542e4f9417d3cd7f232f3d54c1949573aadd0fc";
    }];
    "bc85ddfdfaa94045cdbbb27e73059e302ade763c" = [{
      name = "tzdata2009g";
      url = "https://data.iana.org/time-zones/releases/tzdata2009g.tar.gz";
      sha256 = "da033acc418328edcb32a089c26c1f6a828f596b4f3aa26c9319e3ab19e05073";
    }];
    "91a0e3720eed47131f3607a5a4b409d16b99c24b" = [{
      name = "tzdata2006o";
      url = "https://data.iana.org/time-zones/releases/tzdata2006o.tar.gz";
      sha256 = "89637e234141fb03f5485b1fb7bf871202568c8daf5933e5e4a04b4ceabf3dfa";
    }];
    "9c4dc8d866cf286e5ccedd64c85617e23b82c0fc" = [{
      name = "tzdata1997k";
      url = "https://data.iana.org/time-zones/releases/tzdata1997k.tar.gz";
      sha256 = "c05ff9b2576f9650a8fb0219c3a0b54cf245a5cb48a1eb28ac802b23aca9aa63";
    }];
    "256fcacc2297a699c532ab70eed6f6b4c2acdeee" = [{
      name = "tzdata2005j";
      url = "https://data.iana.org/time-zones/releases/tzdata2005j.tar.gz";
      sha256 = "0d5a71126fe16439eb50552d0734873cbca48ddf9d5143a30a0bfd669f363bae";
    }];
    "6f4fe8b6dce87640ee57c01cba697a9fc19e83f5" = [{
      name = "tzdata2017a";
      url = "https://data.iana.org/time-zones/releases/tzdata2017a.tar.gz";
      sha256 = "df3a5c4d0a2cf0cde0b3f35796ccf6c9acfd598b8e70f8dece5404cd7626bbd6";
    }];
    "7308b495214e2dcaa734093421d2e14fd22fe8a9" = [{
      name = "tzdata2016h";
      url = "https://data.iana.org/time-zones/releases/tzdata2016h.tar.gz";
      sha256 = "da1b74fc2dec2ce8b64948dafb0bfc2f923c830d421a7ae4d016226135697a64";
    }];
    "64f37180776f8cb700eb34fb0177fb7f5edd0a7f" = [{
      name = "tzdata2005k";
      url = "https://data.iana.org/time-zones/releases/tzdata2005k.tar.gz";
      sha256 = "c091080e1562a6c3673ef84e3a988c0d96baeba9959fc55f904b10ff520ee5f6";
    }];
    "dc8c5c0eb7bd707d2adc55407cf624063e34f8e4" = [{
      name = "tzdata2013i";
      url = "https://data.iana.org/time-zones/releases/tzdata2013i.tar.gz";
      sha256 = "1cd56a6ee964143ef0c65229968a5093988335b95e9115235b5e7b7e45e67dda";
    }];
    "139d31d9fc6ea75882b1975a94a9380dcad96fbb" = [{
      name = "tzdata2006l";
      url = "https://data.iana.org/time-zones/releases/tzdata2006l.tar.gz";
      sha256 = "b142459df80b724ca7d8eec0020b1bd97bbbc58f9223b8a3774151cbc5ba48d2";
    }];
    "dcc448b9dfbe2df610cabea89ac31c2c79d944b9" = [{
      name = "tzdata2009k";
      url = "https://data.iana.org/time-zones/releases/tzdata2009k.tar.gz";
      sha256 = "fa82480e7e291b2273c7e4c0bc934aa93bc8567525ff7042cc821db816aa303a";
    }];
    "a925467928d61950a085ba9c4e8203517acb8a57" = [{
      name = "tzdata2010f";
      url = "https://data.iana.org/time-zones/releases/tzdata2010f.tar.gz";
      sha256 = "823361e38da3f79a34c0adb835b1b6d2ae640937e3f7a7f4a2181500eeff0e94";
    }];
    "b973690beafaad07f8fe8172a664e3995665d510" = [{
      name = "tzdata95c";
      url = "https://data.iana.org/time-zones/releases/tzdata95c.tar.gz";
      sha256 = "ab8f40e112941ce906cfa33fe896cedec845db2f2dad7a2d553b4516c4237c4b";
    }];
    "cdf33c168106f747d96cd2e540f971cc9d45bfb0" = [{
      name = "tzdata2006k";
      url = "https://data.iana.org/time-zones/releases/tzdata2006k.tar.gz";
      sha256 = "2d74ecaedd4a8b8c5ee6d74b7fe776ddf5f73fbb6cb39718d3d677d49fba99a5";
    }];
    "bf0d4ff5506df515f443d8bdacffe10f8f04bc35" = [{
      name = "tzdata2009a";
      url = "https://data.iana.org/time-zones/releases/tzdata2009a.tar.gz";
      sha256 = "c704d5a99f4e995b68e0463f206aad38dbddea7e9338d0ccc0abca901dd40100";
    }];
    "4181abd2be1fc8f2964c0681d8bc3ff7d38c299a" = [{
      name = "tzdata95d";
      url = "https://data.iana.org/time-zones/releases/tzdata95d.tar.gz";
      sha256 = "85e3833cb9471de65234ecbac0a57d10681bce98689f22a2e87e97c1be01358f";
    }];
    "532f4b15f6e758737886ddd06c5ab1729db4b187" = [{
      name = "tzdata2009t";
      url = "https://data.iana.org/time-zones/releases/tzdata2009t.tar.gz";
      sha256 = "e9968d213481d7a869ba1afe6167d78d57320364487be9a74e04910a9fce3f85";
    }];
    "5614016e3724d1ed8998394a6126b4661358de44" = [{
      name = "tzdata1998d";
      url = "https://data.iana.org/time-zones/releases/tzdata1998d.tar.gz";
      sha256 = "8991a7066d46f2300f7cdbc59417d256280ec99c3cb563dedab1cce24db23747";
    }];
    "27b5676af22c37a5a99ba78ce516c16639644c03" = [{
      name = "tzdata1997h";
      url = "https://data.iana.org/time-zones/releases/tzdata1997h.tar.gz";
      sha256 = "dba0f910df5fa9dce68d5083847b387fe7551e83d64d127c17f7811a71a79380";
    }];
    "8fdd056255162c5467a36664cd1bbdf681e253e1" = [{
      name = "tzdata2016e";
      url = "https://data.iana.org/time-zones/releases/tzdata2016e.tar.gz";
      sha256 = "ba00f899f18dc4048d7fa21f5e1fdef434496084eedc06f6caa15e5ecdb6bd81";
    }];
    "9719cf7f1bc1a795249ff4c530a98dce586ea0ac" = [{
      name = "tzdata2012b";
      url = "https://data.iana.org/time-zones/releases/tzdata2012b.tar.gz";
      sha256 = "2f9f8e2d1ae087be5917f60c3946e8dc3fe1068d7738c3395f2125135309e745";
    }];
    "201c1199b6c813036cacbf10738e0bc77ba296a1" = [{
      name = "tzdata2010i";
      url = "https://data.iana.org/time-zones/releases/tzdata2010i.tar.gz";
      sha256 = "bee0a26cca54db3413416d968c0a6361d83188b112d2512559d0e3602f254dc3";
    }];
    "00af50ba7c66b49ad97fdf7a529e476aec5039ad" = [{
      name = "tzdata1997b";
      url = "https://data.iana.org/time-zones/releases/tzdata1997b.tar.gz";
      sha256 = "8a6c0801bb2474342a48d6c2253e7983d50d4c6d80a1d455c06fa4e4434df3b3";
    }];
    "ca14bdd73df939e23b617bfc0233b6b4e9098253" = [{
      name = "tzdata2009e";
      url = "https://data.iana.org/time-zones/releases/tzdata2009e.tar.gz";
      sha256 = "6f4e88fefd72b9ed9c6fde56ebc434c86cd597114685bf98ae7aab031a8cce8c";
    }];
    "4dcd67504bc1d9b7ea201b4709a3695ec276f8b8" = [{
      name = "tzdata2005b";
      url = "https://data.iana.org/time-zones/releases/tzdata2005b.tar.gz";
      sha256 = "6a4bc268eff4e4ce9b012cfca9ba1efeb52c9ee5d696f48c9c4b6440929ad40e";
    }];
    "90b27ec406fbe1e30a7b486edde037c7fa475c27" = [{
      name = "tzdata94e";
      url = "https://data.iana.org/time-zones/releases/tzdata94e.tar.gz";
      sha256 = "d02b6b758f50502d2ef233c23a27b2cb3bbe85889b1d5dc3d68c3bafc0d270ca";
    }];
    "7b115993cbb9bf173c5ba9dbdf0bc74d5beccda2" = [{
      name = "tzdata2000c";
      url = "https://data.iana.org/time-zones/releases/tzdata2000c.tar.gz";
      sha256 = "263862e60d7c0ddf93d660489c4250cf0088a306b324b31c25bf6c9ce03916d2";
    }];
    "ddae6fd0e44ad5e8b5088072a4a03fd2c3b67fcb" = [{
      name = "tzdata2007b";
      url = "https://data.iana.org/time-zones/releases/tzdata2007b.tar.gz";
      sha256 = "f1dcc1c615a792c0f72704119faf141e7408f8c94d876e478e052fa33b5a1cb1";
    }];
    "8d770981e2746d6bbc4b70ed98510972e2041106" = [{
      name = "tzdata2018g";
      url = "https://data.iana.org/time-zones/releases/tzdata2018g.tar.gz";
      sha256 = "02dfde534872f6513ae4553a3388fdae579441e31b862ea99170dfc447f46a16";
    }];
    "a891850a4a2a9ff8bedd6d2736dac077bf8309c9" = [{
      name = "tzdata2011l";
      url = "https://data.iana.org/time-zones/releases/tzdata2011l.tar.gz";
      sha256 = "cb9fec68a19c9c3b900bb71f3ca20d0051a863f765387b52fc2d144a5bbb0c7d";
    }];
    "6760b2b88260cce8298d95a98cf2f4d5c044f27b" = [{
      name = "tzdata2016i";
      url = "https://data.iana.org/time-zones/releases/tzdata2016i.tar.gz";
      sha256 = "b6966ec982ef64fe48cebec437096b4f57f4287519ed32dde59c86d3a1853845";
    }];
    "7bf009d1354c839b04424fb830c70dc41dd74be1" = [{
      name = "tzdata2005q";
      url = "https://data.iana.org/time-zones/releases/tzdata2005q.tar.gz";
      sha256 = "d260f2a89499c2ca76ad87d33bad360c9a858b1503a192c71ffea06529716996";
    }];
    "f7b20d08ea0fae0f43fce023421032eb9c839f27" = [{
      name = "tzdata95m";
      url = "https://data.iana.org/time-zones/releases/tzdata95m.tar.gz";
      sha256 = "3574961976fc9762659d145a90b867d30bd88a1978ff65c1f07c7aec26a99e53";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaTime/TimeZones.jl.git"; rev = "4ba8a9579a243400db412b50300cd61d7447e583"; sha256 = "00a04638vj6ay3cdb7qpjrz6zp2ipbinscrxpvdvs382jfvqw9ys"; };
} {
  name = "TimerOutputs";
  uuid = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f";
  path = "T/TimerOutputs";
  replaceUrlInManifest = null;
  treehash = "3318281dd4121ecf9713ce1383b9ace7d7476fdd";
  artifacts = {};
  src = fetchgit { url = "https://github.com/KristofferC/TimerOutputs.jl.git"; rev = "3318281dd4121ecf9713ce1383b9ace7d7476fdd"; sha256 = "1f79rh0q0wk1wj678iwjyq2wzlavca9n0glgwj15i6vhpv0qiggd"; };
} {
  name = "UUIDs";
  uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "UnPack";
  uuid = "3a884ed6-31ef-47d7-9d2a-63182c4928ed";
  path = "U/UnPack";
  replaceUrlInManifest = null;
  treehash = "387c1f73762231e86e0c9c5443ce3b4a0a9a0c2b";
  artifacts = {};
  src = fetchgit { url = "https://github.com/mauro3/UnPack.jl.git"; rev = "387c1f73762231e86e0c9c5443ce3b4a0a9a0c2b"; sha256 = "066v1px72zidnvhl0rczhh07rcfwvli0jx5nprrgyi1dvj3mps2a"; };
} {
  name = "Unicode";
  uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5";
  path = "null";
  replaceUrlInManifest = null;
  treehash = "None";
  artifacts = {};
  src = null;
} {
  name = "XML2_jll";
  uuid = "02c8fc9c-b97f-50b9-bbe4-9be30ff0a78a";
  path = "X/XML2_jll";
  replaceUrlInManifest = null;
  treehash = "be0db24f70aae7e2b89f2f3092e93b8606d659a6";
  artifacts = {
    "595a9c11691838de1f6ed43bfe902f7885cb366a" = [{
      name = "XML2";
      url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl/releases/download/XML2-v2.9.10+0/XML2.v2.9.10.x86_64-linux-gnu.tar.gz";
      sha256 = "5cf1af4a89abb666b0fbafa07fd3748dc05f36f6c57756c8b666f75ec2f0e96b";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/XML2_jll.jl.git"; rev = "be0db24f70aae7e2b89f2f3092e93b8606d659a6"; sha256 = "187acynbivka91dx91qar55dc5zjy3sqi32v4f3p9avhk48i4w97"; };
} {
  name = "Zlib_jll";
  uuid = "83775a58-1f1d-513f-b197-d71354ab007a";
  path = "Z/Zlib_jll";
  replaceUrlInManifest = null;
  treehash = "320228915c8debb12cb434c59057290f0834dbf6";
  artifacts = {
    "27bce23cfb763bc3cc8ccba62ee0a8f67b6f9d9e" = [{
      name = "Zlib";
      url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases/download/Zlib-v1.2.11+13/Zlib.v1.2.11.x86_64-linux-gnu.tar.gz";
      sha256 = "864b11412f28af74c440488cfec2fa0782529f507177c49dddda54eb01185449";
    }];
  };
  src = fetchgit { url = "https://github.com/JuliaBinaryWrappers/Zlib_jll.jl.git"; rev = "320228915c8debb12cb434c59057290f0834dbf6"; sha256 = "0f0dznr9y5zq1yllin61v7qlk8qhac0n71vkmylsjb7bvc77136w"; };
}];
}
